-- Phase V2.3 test harness: create a fully populated draft tournament.
-- Run after the registration migrations.
-- The function is admin-only and does not modify the source tournament.

create or replace function create_seeded_test_tournament(
  source_tournament_id bigint,
  entrant_count integer default 16
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  source_row tournaments%rowtype;
  new_tournament_id bigint;
  test_stamp text := to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS');
  test_name text;
  team_row_id bigint;
  manager_row_id bigint;
  entry_row_id bigint;
  registration_row_id bigint;
  index_value integer;
  rating_value integer;
  group_total integer;
  knockout_total integer;
begin
  if not is_admin() then
    raise exception 'Admin access required';
  end if;

  if entrant_count not in (16, 32, 64) then
    raise exception 'Entrant count must be 16, 32 or 64';
  end if;

  select * into source_row
  from tournaments
  where id = source_tournament_id;

  if not found then
    raise exception 'Source tournament not found';
  end if;

  group_total := ceil(entrant_count::numeric / 4)::integer;
  knockout_total := case
    when entrant_count >= 64 then 32
    when entrant_count >= 32 then 16
    else 8
  end;

  test_name := 'TEST ' || source_row.name || ' ' || test_stamp;

  insert into tournaments (
    season_id,
    competition_id,
    game_world_id,
    competition_type_id,
    season_number,
    name,
    slug,
    public_slug,
    status,
    format,
    source,
    max_entries,
    actual_entries,
    group_count,
    teams_per_group,
    knockout_teams,
    secondary_bracket_name,
    rules_notes,
    is_public,
    archive_quality,
    registration_status,
    registration_opens_at,
    registration_closes_at
  ) values (
    source_row.season_id,
    source_row.competition_id,
    source_row.game_world_id,
    source_row.competition_type_id,
    source_row.season_number,
    test_name,
    'test-' || test_stamp,
    null,
    'draft',
    'groups_then_knockout',
    'app',
    entrant_count,
    entrant_count,
    group_total,
    4,
    knockout_total,
    source_row.secondary_bracket_name,
    'Automatically generated test tournament based on tournament #' || source_tournament_id,
    false,
    'unknown',
    'closed',
    null,
    null
  ) returning id into new_tournament_id;

  for index_value in 1..entrant_count loop
    rating_value := 70 + ((index_value - 1) % 26);

    insert into teams(name, active)
    values (
      'Test Club ' || lpad(index_value::text, 2, '0') || ' ' || test_stamp,
      true
    ) returning id into team_row_id;

    insert into managers(name, display_name, canonical_name, active)
    values (
      'Test Manager ' || lpad(index_value::text, 2, '0') || ' ' || test_stamp,
      'Test Manager ' || lpad(index_value::text, 2, '0'),
      'test-manager-' || lpad(index_value::text, 2, '0') || '-' || test_stamp,
      true
    ) returning id into manager_row_id;

    insert into tournament_entries (
      tournament_id,
      team_id,
      manager_id,
      seed,
      rating,
      entry_status,
      prize_draw_eligible,
      notes
    ) values (
      new_tournament_id,
      team_row_id,
      manager_row_id,
      index_value,
      rating_value,
      'active',
      true,
      'Generated by seeded test tournament harness'
    ) returning id into entry_row_id;

    insert into tournament_registrations (
      tournament_id,
      manager_name,
      manager_email,
      club_name,
      rating,
      notes,
      status,
      manager_key,
      email_key,
      club_key,
      submitted_at,
      reviewed_at,
      reviewed_by,
      promoted_entry_id,
      promoted_at
    ) values (
      new_tournament_id,
      'Test Manager ' || lpad(index_value::text, 2, '0'),
      null,
      'Test Club ' || lpad(index_value::text, 2, '0'),
      rating_value,
      null,
      'approved',
      normal_registration_key('Test Manager ' || lpad(index_value::text, 2, '0')),
      '',
      normal_registration_key('Test Club ' || lpad(index_value::text, 2, '0')),
      now(),
      now(),
      auth.uid(),
      entry_row_id,
      now()
    ) returning id into registration_row_id;
  end loop;

  return new_tournament_id;
end;
$$;

grant execute on function create_seeded_test_tournament(bigint, integer) to authenticated;
