import { createClient } from '@supabase/supabase-js';

const CHALLONGE_V2_BASE_URL = 'https://api.challonge.com/v2.1';
const CHALLONGE_V1_BASE_URL = 'https://api.challonge.com/v1';
const CHALLONGE_HEADERS = { Accept: 'application/json', 'Content-Type': 'application/vnd.api+json', 'Authorization-Type': 'v1' };

function json(statusCode, body) {
  return { statusCode, headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS' }, body: JSON.stringify(body, null, 2) };
}
function requiredEnv(name) { const value = String(process.env[name] || '').trim(); if (!value) throw new Error(`Missing environment variable: ${name}`); return value; }
function getSupabase() { const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY; if (!key) throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY or VITE_SUPABASE_ANON_KEY'); return createClient(requiredEnv('VITE_SUPABASE_URL'), key, { auth: { persistSession: false } }); }
function apiKey() { return requiredEnv('CHALLONGE_API_KEY'); }
async function fetchJson(url, options = {}) { const response = await fetch(url, options); const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = { raw: text }; } if (!response.ok) { const error = new Error(data?.errors?.detail || data?.errors?.[0]?.detail || data?.message || data?.error || text || `${response.status} ${response.statusText}`); error.statusCode = response.status; error.url = url; throw error; } return data; }
function ensureJsonPath(path) { if (path.includes('?') || path.endsWith('.json')) return path; return `${path}.json`; }
async function challongeGetV2(path, query = {}) { const url = new URL(`${CHALLONGE_V2_BASE_URL}${ensureJsonPath(path)}`); Object.entries(query).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') url.searchParams.set(k, v); }); return fetchJson(url.toString(), { headers: { ...CHALLONGE_HEADERS, Authorization: apiKey() } }); }
async function challongeGetV1(path, query = {}) { const url = new URL(`${CHALLONGE_V1_BASE_URL}${ensureJsonPath(path)}`); url.searchParams.set('api_key', apiKey()); Object.entries(query).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') url.searchParams.set(k, v); }); return fetchJson(url.toString(), { headers: { Accept: 'application/json' } }); }
async function firstSuccessful(requests) { const errors = []; for (const request of requests) { try { return { source: request.source, data: await request.run() }; } catch (error) { errors.push({ source: request.source, message: error.message, statusCode: error.statusCode }); } } const error = new Error(errors.map((x) => `${x.source}: ${x.message}`).join(' | ')); error.attempts = errors; throw error; }
function asArray(payload) { if (Array.isArray(payload?.data)) return payload.data; if (Array.isArray(payload?.tournaments)) return payload.tournaments; if (Array.isArray(payload?.participants)) return payload.participants; if (Array.isArray(payload?.matches)) return payload.matches; if (Array.isArray(payload)) return payload; return payload?.data ? [payload.data] : []; }
function attrs(item) { return item?.attributes || item?.tournament || item?.participant || item?.match || item || {}; }
function itemId(item) { const a = attrs(item); return String(item?.id || a.id || item?.tournament?.id || item?.participant?.id || item?.match?.id || '').trim(); }
function relationId(item, ...keys) { for (const key of keys) { const direct = item?.[key] ?? item?.attributes?.[key] ?? item?.match?.[key] ?? item?.participant?.[key]; if (direct !== undefined && direct !== null) return String(direct); const rel = item?.relationships?.[key]?.data; if (rel?.id !== undefined && rel?.id !== null) return String(rel.id); } return null; }
function tournamentName(tournament) { const a = attrs(tournament); return String(a.name || a.full_name || a.fullName || tournament.name || `Challonge ${itemId(tournament)}`).trim(); }
function participantName(participant) { const a = attrs(participant); return String(a.name || a.display_name || a.displayName || a.username || participant.name || `Participant ${itemId(participant)}`).trim(); }
function parseTeamAndManager(name) { const clean = String(name || '').trim(); const bracketed = clean.match(/^(.*?)\s*[–—-]?\s*\((.*?)\)\s*$/); if (bracketed) return { teamName: bracketed[1].trim() || clean, managerName: bracketed[2].trim() || 'TBC Manager' }; return { teamName: clean, managerName: 'TBC Manager' }; }
function parseScores(match) { const a = attrs(match); const scores = a.scores_csv || a.scoresCsv || a.score_csv || a.scoreCsv || a.scores || a.score; if (typeof scores === 'string') { const found = scores.split(',')[0].trim().match(/(-?\d+)\s*[-:]\s*(-?\d+)/); if (found) return { home_score: Number(found[1]), away_score: Number(found[2]) }; } const home = a.player1_score ?? a.player1Score ?? a.home_score ?? a.homeScore ?? a.team1_score ?? a.team1Score; const away = a.player2_score ?? a.player2Score ?? a.away_score ?? a.awayScore ?? a.team2_score ?? a.team2Score; if (home !== undefined && away !== undefined && home !== null && away !== null) return { home_score: Number(home), away_score: Number(away) }; return { home_score: null, away_score: null }; }
function matchRound(match) { const raw = attrs(match).round ?? attrs(match).round_number ?? attrs(match).roundNumber ?? attrs(match).identifier ?? 'Round'; const number = Number(raw); if (Number.isFinite(number)) { if (number < 0) return `Losers R${Math.abs(number)}`; if (number === 1) return 'R32'; if (number === 2) return 'R16'; if (number === 3) return 'QF'; if (number === 4) return 'SF'; if (number >= 5) return 'Final'; } return String(raw || 'Round'); }
function matchOrder(match, index) { const a = attrs(match); return Number(a.suggested_play_order || a.suggestedPlayOrder || a.match_order || a.matchOrder || a.identifier || index + 1) || index + 1; }
function matchStatus(match, score) { const state = String(attrs(match).state || attrs(match).status || '').toLowerCase(); if (state.includes('complete') || state.includes('played') || state === 'closed') return 'played'; if (Number.isFinite(score.home_score) && Number.isFinite(score.away_score)) return 'played'; return 'scheduled'; }
function cleanUnique(values) { return [...new Set(values.map((v) => String(v || '').trim()).filter(Boolean))]; }
async function selectByNames(supabase, table, names) { if (!names.length) return []; const { data, error } = await supabase.from(table).select('id, name').in('name', names); if (error) throw error; return data || []; }
async function insertRows(supabase, table, rows) { if (!rows.length) return []; const { data, error } = await supabase.from(table).insert(rows).select('id, name'); if (error) throw error; return data || []; }
async function findOrCreateOne(supabase, table, match, row) { const existing = await supabase.from(table).select('id').match(match).maybeSingle(); if (existing.error) throw existing.error; if (existing.data) return existing.data.id; const created = await supabase.from(table).insert(row).select('id').single(); if (created.error) throw created.error; return created.data.id; }
async function loadBundle(challongeTournamentId) { return firstSuccessful([{ source: 'v2.1 headers', run: async () => ({ tournament: await challongeGetV2(`/tournaments/${encodeURIComponent(challongeTournamentId)}`), participants: await challongeGetV2(`/tournaments/${encodeURIComponent(challongeTournamentId)}/participants`, { 'page[size]': 250 }), matches: await challongeGetV2(`/tournaments/${encodeURIComponent(challongeTournamentId)}/matches`, { 'page[size]': 250 }) }) }, { source: 'legacy v1 query api_key', run: async () => ({ tournament: await challongeGetV1(`/tournaments/${encodeURIComponent(challongeTournamentId)}`), participants: await challongeGetV1(`/tournaments/${encodeURIComponent(challongeTournamentId)}/participants`), matches: await challongeGetV1(`/tournaments/${encodeURIComponent(challongeTournamentId)}/matches`) }) }]); }
function normalizedBundle(bundle) { const tournament = asArray(bundle.data.tournament)[0] || bundle.data.tournament?.tournament || bundle.data.tournament?.data || bundle.data.tournament; const participants = asArray(bundle.data.participants); const matches = asArray(bundle.data.matches); const parsedParticipants = participants.map((p, index) => { const parsed = parseTeamAndManager(participantName(p)); return { challongeParticipantId: itemId(p), seed: Number(attrs(p).seed || attrs(p).rank || index + 1) || index + 1, ...parsed }; }); return { source: bundle.source, tournament, participants, matches, parsedParticipants } }
async function listTournaments(event) { const page = event.queryStringParameters?.page || '1'; const perPage = event.queryStringParameters?.perPage || '25'; const result = await firstSuccessful([{ source: 'v2.1 headers, no pagination', run: () => challongeGetV2('/tournaments') }, { source: 'v2.1 headers, simple pagination', run: () => challongeGetV2('/tournaments', { page, per_page: perPage }) }, { source: 'legacy v1 query api_key', run: () => challongeGetV1('/tournaments', { page, per_page: perPage }) }]); return json(200, { ok: true, authMode: result.source, tournaments: asArray(result.data).map((item) => ({ id: itemId(item), name: tournamentName(item), attributes: attrs(item) })) }); }
async function previewTournament(body) { const challongeTournamentId = String(body.challongeTournamentId || body.tournamentId || '').trim(); if (!challongeTournamentId) return json(400, { ok: false, error: 'Missing challongeTournamentId' }); const bundle = normalizedBundle(await loadBundle(challongeTournamentId)); const name = body.tournamentName || tournamentName(bundle.tournament); return json(200, { ok: true, mode: 'preview', authMode: bundle.source, challongeTournamentId, tournamentName: name, participantsCount: bundle.parsedParticipants.length, matchesCount: bundle.matches.length, sampleParticipants: bundle.parsedParticipants.slice(0, 12), sampleMatches: bundle.matches.slice(0, 8).map((m, i) => ({ id: itemId(m), round: matchRound(m), order: matchOrder(m, i), score: parseScores(m), status: matchStatus(m, parseScores(m)) })) }); }
async function importTournament(body) { const challongeTournamentId = String(body.challongeTournamentId || body.tournamentId || '').trim(); if (!challongeTournamentId) return json(400, { ok: false, error: 'Missing challongeTournamentId' }); const supabase = getSupabase(); const bundle = normalizedBundle(await loadBundle(challongeTournamentId)); const importedTournamentName = body.tournamentName || tournamentName(bundle.tournament); const seasonCode = body.seasonCode || 'Imported'; const competitionName = body.competitionName || 'Challonge Import';
  const seasonNumber = Number(String(seasonCode).replace(/[^0-9]/g, '')) || null; const seasonId = await findOrCreateOne(supabase, 'seasons', { code: seasonCode }, { code: seasonCode, number: seasonNumber }); const competitionId = await findOrCreateOne(supabase, 'competitions', { name: competitionName }, { name: competitionName, competition_type: body.competitionType || 'imported' });
  const existingTournament = await supabase.from('tournaments').select('id').eq('source', 'challonge').eq('source_id', challongeTournamentId).maybeSingle(); if (existingTournament.error) throw existingTournament.error; let tournamentId = existingTournament.data?.id; const tournamentRow = { season_id: seasonId, competition_id: competitionId, name: importedTournamentName, status: body.status || 'archived', format: body.format || 'challonge_import', source: 'challonge', source_id: challongeTournamentId, max_entries: bundle.parsedParticipants.length, actual_entries: bundle.parsedParticipants.length, group_count: body.groupCount || null, teams_per_group: body.teamsPerGroup || null, knockout_teams: body.knockoutTeams || null, secondary_bracket_name: body.secondaryBracketName || null, rules_notes: `Imported from Challonge API using ${bundle.source}` }; if (!tournamentId) { const created = await supabase.from('tournaments').insert(tournamentRow).select('id').single(); if (created.error) throw created.error; tournamentId = created.data.id; } else { const updated = await supabase.from('tournaments').update(tournamentRow).eq('id', tournamentId); if (updated.error) throw updated.error; }
  const teamNames = cleanUnique(bundle.parsedParticipants.map((p) => p.teamName)); const managerNames = cleanUnique(bundle.parsedParticipants.map((p) => p.managerName)); let teams = await selectByNames(supabase, 'teams', teamNames); await insertRows(supabase, 'teams', teamNames.filter((name) => !teams.some((t) => t.name === name)).map((name) => ({ name, active: true }))); teams = await selectByNames(supabase, 'teams', teamNames); let managers = await selectByNames(supabase, 'managers', managerNames); await insertRows(supabase, 'managers', managerNames.filter((name) => !managers.some((m) => m.name === name)).map((name) => ({ name, display_name: name, canonical_name: name.toLowerCase(), active: true }))); managers = await selectByNames(supabase, 'managers', managerNames);
  const teamMap = new Map(teams.map((t) => [t.name, t.id])); const managerMap = new Map(managers.map((m) => [m.name, m.id])); const existingEntriesResult = await supabase.from('tournament_entries').select('id, team_id').eq('tournament_id', tournamentId); if (existingEntriesResult.error) throw existingEntriesResult.error; const existingEntryByTeam = new Map((existingEntriesResult.data || []).map((e) => [e.team_id, e.id])); const newEntries = bundle.parsedParticipants.filter((p) => !existingEntryByTeam.has(teamMap.get(p.teamName))).map((p) => ({ tournament_id: tournamentId, team_id: teamMap.get(p.teamName), manager_id: managerMap.get(p.managerName), seed: p.seed, rating: null, entry_status: 'active', prize_draw_eligible: true, notes: `challonge_participant_id:${p.challongeParticipantId}` })); if (newEntries.length) { const inserted = await supabase.from('tournament_entries').insert(newEntries).select('id, team_id'); if (inserted.error) throw inserted.error; inserted.data.forEach((e) => existingEntryByTeam.set(e.team_id, e.id)); }
  const participantToEntry = new Map(bundle.parsedParticipants.map((p) => [p.challongeParticipantId, existingEntryByTeam.get(teamMap.get(p.teamName))])); await supabase.from('matches').delete().eq('tournament_id', tournamentId).eq('source_id', challongeTournamentId);
  const matchRows = bundle.matches.map((match, index) => { const a = attrs(match); const player1 = relationId(match, 'player1', 'player1_id', 'player1Id', 'participant1', 'participant1_id', 'participant1Id'); const player2 = relationId(match, 'player2', 'player2_id', 'player2Id', 'participant2', 'participant2_id', 'participant2Id'); const score = parseScores(match); const status = matchStatus(match, score); const winner = relationId(match, 'winner', 'winner_id', 'winnerId'); const loser = relationId(match, 'loser', 'loser_id', 'loserId'); const homeEntryId = player1 ? participantToEntry.get(String(player1)) : null; const awayEntryId = player2 ? participantToEntry.get(String(player2)) : null; return { tournament_id: tournamentId, stage: body.stage || 'knockout', round: body.round || matchRound(match), leg: 1, match_order: matchOrder(match, index), scheduled_at: a.scheduled_time || a.scheduledTime || null, fixture_date: a.scheduled_time ? String(a.scheduled_time).slice(0, 10) : null, home_entry_id: homeEntryId || null, away_entry_id: awayEntryId || null, home_placeholder: homeEntryId ? null : (player1 ? `Challonge participant ${player1}` : 'TBC'), away_placeholder: awayEntryId ? null : (player2 ? `Challonge participant ${player2}` : 'TBC'), home_score: Number.isFinite(score.home_score) ? score.home_score : null, away_score: Number.isFinite(score.away_score) ? score.away_score : null, winner_entry_id: winner ? participantToEntry.get(String(winner)) || null : null, loser_entry_id: loser ? participantToEntry.get(String(loser)) || null : null, status, source_id: challongeTournamentId, challonge_match_id: itemId(match) || String(index + 1), bracket: body.bracket || 'Cup', played_at: status === 'played' ? (a.completed_at || a.completedAt || new Date().toISOString()) : null, published: true }; });
  let importedMatches = 0; for (let i = 0; i < matchRows.length; i += 500) { const chunk = matchRows.slice(i, i + 500); if (chunk.length) { const inserted = await supabase.from('matches').insert(chunk); if (inserted.error) throw inserted.error; importedMatches += chunk.length; } }
  return json(200, { ok: true, mode: 'import', authMode: bundle.source, tournamentId, importedTournamentName, importedParticipants: bundle.parsedParticipants.length, importedMatches, updatedMatches: 0, challongeTournamentId }); }
export async function handler(event) { if (event.httpMethod === 'OPTIONS') return json(200, { ok: true }); try { if (event.httpMethod === 'GET') return await listTournaments(event); if (event.httpMethod === 'POST') { const body = JSON.parse(event.body || '{}'); return body.action === 'preview' ? await previewTournament(body) : await importTournament(body); } return json(405, { ok: false, error: 'Method not allowed' }); } catch (error) { console.error(error); return json(500, { ok: false, error: error.message, attempts: error.attempts || undefined }); } }
