import { useEffect, useMemo, useState } from 'react';
import FixturesManager from './FixturesManager.jsx';
import KnockoutScheduleManager from './KnockoutScheduleManager.jsx';
import { hasSupabaseConfig, supabase } from '../lib/supabaseClient';

const ROUND_ORDER = ['R32', 'R16', 'QF', 'SF', 'Final'];
const NEXT_ROUND = { R32: 'R16', R16: 'QF', QF: 'SF', SF: 'Final' };
function isCompleted(match) { return match.status === 'played' || match.status === 'forfeit'; }
function entryName(entries, entryId, fallback) { const entry = entries.find((item) => item.id === entryId); return entry?.teams?.name || fallback || 'TBC'; }
function dataSort(matches) { return [...matches].sort((a, b) => String(a.bracket || '').localeCompare(String(b.bracket || '')) || roundIndex(a.round) - roundIndex(b.round) || Number(a.match_order || 0) - Number(b.match_order || 0) || Number(a.leg || 1) - Number(b.leg || 1)); }
function roundIndex(round) { const i = ROUND_ORDER.indexOf(round); return i === -1 ? 99 : i; }
function blankRow(entry) { return { entry_id: entry.id, seed: entry.seed, team_name: entry.teams?.name || 'Unknown team', manager_name: entry.managers?.display_name || entry.managers?.name || 'TBC', group_code: entry.group_code, played: 0, wins: 0, draws: 0, losses: 0, goals_for: 0, goals_against: 0, goal_difference: 0, points: 0 }; }
function compareRows(a, b) { return b.points - a.points || b.goal_difference - a.goal_difference || b.goals_for - a.goals_for || Number(a.seed || 999) - Number(b.seed || 999) || a.team_name.localeCompare(b.team_name); }
function buildTables(entries, matches) { const byGroup = entries.reduce((groups, entry) => { const code = entry.group_code || 'Ungrouped'; if (!groups[code]) groups[code] = []; groups[code].push(entry); return groups; }, {}); return Object.entries(byGroup).sort(([a], [b]) => a.localeCompare(b)).map(([groupCode, groupEntries]) => { const rowsById = new Map(groupEntries.map((entry) => [entry.id, blankRow(entry)])); matches.filter((match) => (match.groups?.code || groupCode) === groupCode).filter(isCompleted).forEach((match) => { const home = rowsById.get(match.home_entry_id); const away = rowsById.get(match.away_entry_id); if (!home || !away) return; const hs = Number(match.home_score || 0); const as = Number(match.away_score || 0); home.played += 1; away.played += 1; home.goals_for += hs; home.goals_against += as; away.goals_for += as; away.goals_against += hs; if (hs > as) { home.wins += 1; home.points += 3; away.losses += 1; } else if (as > hs) { away.wins += 1; away.points += 3; home.losses += 1; } else { home.draws += 1; away.draws += 1; home.points += 1; away.points += 1; } }); const rows = [...rowsById.values()].map((row) => ({ ...row, goal_difference: row.goals_for - row.goals_against })).sort(compareRows).map((row, index) => ({ ...row, group_position: index + 1 })); return { groupCode, rows }; }); }
function seedQualifiers(tables, position) { return tables.flatMap((table) => table.rows.filter((row) => row.group_position === position)).sort(compareRows).map((row, index) => ({ ...row, knockout_seed: index + 1 })); }
function bracketRound(matches, bracket, round) { return dataSort(matches.filter((match) => match.stage === 'knockout' && match.bracket === bracket && match.round === round)); }
function legCount(bracket, round) { if (bracket === 'Cup') return round === 'R32' ? 1 : 2; if (bracket === 'Shield') return round === 'R32' || round === 'R16' ? 1 : 2; return 1; }
function testKnockoutScore(match) { const base = Number(match.match_order || 1) + Number(match.leg || 1) + (match.bracket === 'Shield' ? 2 : 0); const home = (base % 4) + 1; const away = base % 3; return home === away ? { home_score: home + 1, away_score: away } : { home_score: home, away_score: away }; }
function winnerLoserFor(match, homeScore, awayScore) { if (homeScore > awayScore) return { winner_entry_id: match.home_entry_id, loser_entry_id: match.away_entry_id }; if (awayScore > homeScore) return { winner_entry_id: match.away_entry_id, loser_entry_id: match.home_entry_id }; return { winner_entry_id: null, loser_entry_id: null }; }
function resolveTie(legs) { const ordered = dataSort(legs); if (ordered.some((leg) => !isCompleted(leg))) return { reason: 'incomplete' }; const first = ordered[0]; const firstId = first.home_entry_id; const secondId = first.away_entry_id; let firstAgg = 0, secondAgg = 0, firstAway = 0, secondAway = 0; ordered.forEach((leg) => { const hs = Number(leg.home_score || 0); const as = Number(leg.away_score || 0); if (leg.home_entry_id === firstId) { firstAgg += hs; secondAgg += as; secondAway += as; } else { firstAgg += as; secondAgg += hs; firstAway += as; } }); if (firstAgg > secondAgg) return { winnerId: firstId, loserId: secondId }; if (secondAgg > firstAgg) return { winnerId: secondId, loserId: firstId }; if (ordered.length > 1 && firstAway > secondAway) return { winnerId: firstId, loserId: secondId }; if (ordered.length > 1 && secondAway > firstAway) return { winnerId: secondId, loserId: firstId }; return { reason: 'fet_required' }; }
function tieWinners(source) { const ties = new Map(); source.forEach((match) => { if (!ties.has(match.match_order)) ties.set(match.match_order, []); ties.get(match.match_order).push(match); }); const winners = [], unresolved = []; [...ties.entries()].sort(([a], [b]) => Number(a) - Number(b)).forEach(([matchOrder, legs]) => { const result = resolveTie(legs); if (result.winnerId) winners.push(result.winnerId); else unresolved.push({ matchOrder, reason: result.reason }); }); return { winners, unresolved }; }
function nextRoundLabel(matches, bracket) { const existing = ROUND_ORDER.filter((round) => bracketRound(matches, bracket, round).length > 0); const latest = existing[existing.length - 1]; const next = NEXT_ROUND[latest]; return next ? `Generate ${bracket} ${next}` : `Next ${bracket} round`; }

export default function KnockoutManager({ selectedTournament, onDataChanged }) {
  const [entries, setEntries] = useState([]), [matches, setMatches] = useState([]), [presets, setPresets] = useState([]), [status, setStatus] = useState('Ready'), [loading, setLoading] = useState(false);
  const tournamentId = selectedTournament?.id;
  useEffect(() => { if (hasSupabaseConfig && supabase && tournamentId) loadData(); }, [tournamentId]);
  const groupMatches = matches.filter((match) => match.stage === 'group');
  const knockoutMatches = matches.filter((match) => match.stage === 'knockout');
  const playedGroupMatches = groupMatches.filter(isCompleted);
  const groupComplete = groupMatches.length > 0 && playedGroupMatches.length === groupMatches.length;
  const tables = useMemo(() => buildTables(entries, groupMatches), [entries, groupMatches]);
  const cupQualifiers = useMemo(() => seedQualifiers(tables, 1).concat(seedQualifiers(tables, 2)).sort((a, b) => a.knockout_seed - b.knockout_seed), [tables]);
  const shieldHomeTeams = useMemo(() => seedQualifiers(tables, 3).sort((a, b) => a.knockout_seed - b.knockout_seed), [tables]);
  async function loadData() { if (!tournamentId) return; setLoading(true); const [entriesResult, matchesResult, presetsResult] = await Promise.all([supabase.from('tournament_entries').select('id, tournament_id, team_id, manager_id, seed, rating, group_code, pot, teams(id, name), managers(id, name, display_name)').eq('tournament_id', tournamentId).order('seed', { ascending: true }), supabase.from('matches').select('id, tournament_id, group_id, stage, round, leg, match_order, fixture_date, home_entry_id, away_entry_id, home_score, away_score, winner_entry_id, loser_entry_id, status, bracket, home_placeholder, away_placeholder, groups(id, code, name)').eq('tournament_id', tournamentId).order('stage', { ascending: true }).order('bracket', { ascending: true }).order('round', { ascending: true }).order('match_order', { ascending: true }).order('leg', { ascending: true }), supabase.from('tournament_round_dates').select('bracket, round, leg1_date, leg2_date').eq('tournament_id', tournamentId)]); if (entriesResult.error) setStatus('Could not load entrants: ' + entriesResult.error.message); else if (matchesResult.error) setStatus('Could not load matches: ' + matchesResult.error.message); else { setEntries(entriesResult.data || []); setMatches(dataSort(matchesResult.data || [])); setPresets(presetsResult.error ? [] : presetsResult.data || []); setStatus(presetsResult.error ? 'Knockout data loaded. Schedule presets table not found yet.' : 'Knockout data loaded from database.'); } setLoading(false); }
  function dateFor(bracket, round, leg) { const preset = presets.find((item) => item.bracket === bracket && item.round === round); if (!preset) return null; return Number(leg) === 2 ? preset.leg2_date : preset.leg1_date; }
  async function insertMatches(rows, successMessage) { setLoading(true); const { error } = await supabase.from('matches').insert(rows); if (error) setStatus('Save failed: ' + error.message); else { setStatus(successMessage); await loadData(); await onDataChanged?.(); } setLoading(false); }
  async function saveCupR32() { if (!groupComplete) return setStatus('Group stage is not complete yet.'); if (bracketRound(knockoutMatches, 'Cup', 'R32').length > 0) return setStatus('Cup R32 already exists.'); const rows = []; cupQualifiers.forEach((home, index) => { if (index >= Math.floor(cupQualifiers.length / 2)) return; const away = cupQualifiers[cupQualifiers.length - 1 - index]; rows.push({ tournament_id: tournamentId, stage: 'knockout', round: 'R32', leg: 1, match_order: index + 1, home_entry_id: home.entry_id, away_entry_id: away.entry_id, home_placeholder: home.team_name, away_placeholder: away.team_name, bracket: 'Cup', fixture_date: dateFor('Cup', 'R32', 1), status: 'scheduled' }); }); await insertMatches(rows, 'Cup R32 saved.'); }
  async function saveShieldR32() { const cupR32 = bracketRound(knockoutMatches, 'Cup', 'R32'); if (!cupR32.length) return setStatus('Generate Cup R32 first.'); if (cupR32.some((match) => !isCompleted(match) || !match.loser_entry_id)) return setStatus('Finish Cup R32 first.'); if (bracketRound(knockoutMatches, 'Shield', 'R32').length > 0) return setStatus('Shield R32 already exists.'); const losers = cupR32.map((match, index) => ({ entry_id: match.loser_entry_id, team_name: entryName(entries, match.loser_entry_id, 'Cup loser ' + (index + 1)) })); const rows = shieldHomeTeams.map((home, index) => { const away = losers[losers.length - 1 - index]; return { tournament_id: tournamentId, stage: 'knockout', round: 'R32', leg: 1, match_order: index + 1, home_entry_id: home.entry_id, away_entry_id: away.entry_id, home_placeholder: home.team_name, away_placeholder: away.team_name, bracket: 'Shield', fixture_date: dateFor('Shield', 'R32', 1), status: 'scheduled' }; }); await insertMatches(rows, 'Shield R32 saved.'); }
  async function autoFillKnockout() { const targets = knockoutMatches.filter((match) => !isCompleted(match)); if (!targets.length) return setStatus('No outstanding knockout fixtures to auto-fill.'); setLoading(true); for (const match of targets) { const score = testKnockoutScore(match); const result = winnerLoserFor(match, score.home_score, score.away_score); const { error } = await supabase.from('matches').update({ ...score, ...result, status: 'played', played_at: new Date().toISOString() }).eq('id', match.id); if (error) { setStatus('Auto-fill failed: ' + error.message); setLoading(false); return; } } await loadData(); await onDataChanged?.(); setStatus(targets.length + ' knockout test result(s) saved.'); setLoading(false); }
  async function generateNextRound(bracket) { const existing = ROUND_ORDER.filter((round) => bracketRound(knockoutMatches, bracket, round).length > 0); const latest = existing[existing.length - 1]; const next = NEXT_ROUND[latest]; if (!latest || !next) return setStatus('No next round is available for ' + bracket + '.'); if (bracketRound(knockoutMatches, bracket, next).length > 0) return setStatus(next + ' already exists for ' + bracket + '.'); const { winners, unresolved } = tieWinners(bracketRound(knockoutMatches, bracket, latest)); if (unresolved.length) return setStatus('Cannot generate ' + bracket + ' ' + next + ': unresolved ties remain.'); const rows = []; const legs = legCount(bracket, next); for (let index = 0; index < winners.length; index += 2) { const homeId = winners[index], awayId = winners[index + 1]; if (!awayId) continue; const order = index / 2 + 1; rows.push({ tournament_id: tournamentId, stage: 'knockout', round: next, leg: 1, match_order: order, home_entry_id: homeId, away_entry_id: awayId, home_placeholder: entryName(entries, homeId, 'Winner ' + (index + 1)), away_placeholder: entryName(entries, awayId, 'Winner ' + (index + 2)), bracket, fixture_date: dateFor(bracket, next, 1), status: 'scheduled' }); if (legs === 2) rows.push({ tournament_id: tournamentId, stage: 'knockout', round: next, leg: 2, match_order: order, home_entry_id: awayId, away_entry_id: homeId, home_placeholder: entryName(entries, awayId, 'Winner ' + (index + 2)), away_placeholder: entryName(entries, homeId, 'Winner ' + (index + 1)), bracket, fixture_date: dateFor(bracket, next, 2), status: 'scheduled' }); } await insertMatches(rows, bracket + ' ' + next + ' generated.'); }
  if (!selectedTournament) return <p className="muted">Create or select a tournament first.</p>; if (!hasSupabaseConfig || !supabase) return <p className="muted">Supabase is not connected yet.</p>;
  return <div className="knockout-manager"><div className="fixtures-toolbar"><div><p className="eyebrow">Knockout generator</p><h3>{playedGroupMatches.length} / {groupMatches.length} group fixtures played</h3><p className="muted">Knockout seeding uses group finishing position: best group winners vs lowest qualifying second-placed sides, then aggregates, away goals and FET as needed.</p></div><div className="button-row"><button type="button" className="secondary" onClick={loadData} disabled={loading}>Reload knockout data</button><button type="button" onClick={saveCupR32} disabled={loading || !groupComplete}>Generate Cup R32</button><button type="button" className="secondary" onClick={autoFillKnockout} disabled={loading || knockoutMatches.every(isCompleted)}>Auto-fill knockout test scores</button><button type="button" className="secondary" onClick={saveShieldR32} disabled={loading}>Generate Shield R32</button><button type="button" className="secondary" onClick={() => generateNextRound('Cup')} disabled={loading}>{nextRoundLabel(knockoutMatches, 'Cup')}</button><button type="button" className="secondary" onClick={() => generateNextRound('Shield')} disabled={loading}>{nextRoundLabel(knockoutMatches, 'Shield')}</button></div></div><p className="status">{status}</p><div className={groupComplete ? 'ready-banner ready' : 'ready-banner'}><strong>{groupComplete ? 'Group stage complete.' : 'Group stage not complete yet.'}</strong><span>{groupComplete ? 'Cup R32 can be generated if it does not already exist.' : 'Finish all group fixtures before saving the knockout draw.'}</span></div><KnockoutScheduleManager selectedTournament={selectedTournament} onDataChanged={async () => { await loadData(); await onDataChanged?.(); }} /><section className="bracket-grid knockout-bracket-grid"><BracketColumn title="Saved Cup" type="cup" matches={knockoutMatches.filter((match) => match.bracket === 'Cup')} /><BracketColumn title="Saved Shield" type="shield" matches={knockoutMatches.filter((match) => match.bracket === 'Shield')} /></section><section className="knockout-desk-grid"><article className="knockout-desk-card fixtures-card"><h3>Knockout fixtures</h3><p className="muted">Unplayed Cup and Shield matches.</p><FixturesManager selectedTournament={selectedTournament} stage="knockout" onlyOutstanding onDataChanged={onDataChanged} /></article><article className="knockout-desk-card results-card"><h3>Knockout results</h3><p className="muted">Played Cup and Shield matches.</p><FixturesManager selectedTournament={selectedTournament} stage="knockout" onlyCompleted onDataChanged={onDataChanged} /></article></section></div>;
}
function BracketColumn({ title, type, matches }) { const rounds = ROUND_ORDER.filter((round) => matches.some((match) => match.round === round)); return <article className={'bracket-section bracket-' + type}><h3>{title}</h3>{rounds.length === 0 ? <p className="muted">No saved matches yet.</p> : rounds.map((round) => <div key={round} className="round-block"><h4>{round}</h4><KnockoutList matches={dataSort(matches.filter((match) => match.round === round))} /></div>)}</article>; }
function KnockoutList({ matches }) { if (!matches.length) return <p className="muted">No matches yet.</p>; return <div className="knockout-list">{matches.map((match) => <article className={isCompleted(match) ? 'knockout-card played' : 'knockout-card'} key={(match.bracket || 'draw') + '-' + match.round + '-' + match.match_order + '-' + (match.leg || 1) + '-' + match.home_entry_id}><span>{match.bracket || 'Knockout'} · {match.round || 'Round'}{match.leg ? ' · ' + (Number(match.leg) === 1 ? '1st leg' : '2nd leg') : ''}</span><strong>{match.home_placeholder}</strong><em>{isCompleted(match) ? `${match.home_score} - ${match.away_score}` : 'v'}</em><strong>{match.away_placeholder}</strong></article>)}</div>; }
