-- Canonicalise Soccer Manager club labels against the Top 100 team directory
-- without discarding the raw names captured from Soccer Manager.
--
-- Resolution order:
--   1. explicit learned aliases
--   2. exact normalized team-directory match
--   3. exact normalized canonical game-world club match
--   4. learned Manager Portal team alias
--   5. raw source name fallback

create table if not exists public.soccer_manager_team_aliases (
  id bigint generated by default as identity primary key,
  game_world_id bigint not null references public.game_worlds(id) on delete cascade,
  source_name text not null,
  source_key text not null,
  team_id bigint not null references public.teams(id) on delete cascade,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_world_id, source_key)
);

create index if not exists soccer_manager_team_aliases_team_idx
  on public.soccer_manager_team_aliases(team_id);

alter table public.soccer_manager_team_aliases enable row level security;

revoke all on public.soccer_manager_team_aliases from public, anon;
grant select, insert, update, delete on public.soccer_manager_team_aliases to authenticated, service_role;

create policy "Admins manage Soccer Manager team aliases"
  on public.soccer_manager_team_aliases
  for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create or replace function public.resolve_soccer_manager_team(
  target_game_world_id bigint,
  source_name text
)
returns table (
  team_id bigint,
  canonical_name text,
  resolution text
)
language sql
stable
security definer
set search_path = public
as $$
  with input as (
    select
      target_game_world_id as game_world_id,
      nullif(trim(source_name), '') as raw_name,
      public.team_directory_key(source_name) as source_key,
      public.normalise_manager_claim_text(source_name) as alias_key
  ),
  resolved as (
    select a.team_id, t.name as canonical_name, 1 as priority, 'soccer_manager_alias'::text as resolution
    from input i
    join public.soccer_manager_team_aliases a
      on a.game_world_id = i.game_world_id and a.source_key = i.source_key
    join public.teams t on t.id = a.team_id

    union all

    select t.id, t.name, 2, 'team_directory_exact'
    from input i
    join public.teams t on public.team_directory_key(t.name) = i.source_key
    where i.source_key <> ''

    union all

    select t.id, t.name, 3, 'game_world_directory_exact'
    from input i
    join public.game_world_clubs g
      on g.game_world_id = i.game_world_id
     and g.active = true
     and public.team_directory_key(g.club_name) = i.source_key
    join public.teams t on public.team_directory_key(t.name) = public.team_directory_key(g.club_name)
    where i.source_key <> ''

    union all

    select a.team_id, t.name, 4, 'manager_team_alias'
    from input i
    join public.manager_team_aliases a on a.alias_key = i.alias_key
    join public.teams t on t.id = a.team_id
    where i.alias_key <> ''
  )
  select r.team_id, r.canonical_name, r.resolution
  from resolved r
  order by r.priority, r.team_id
  limit 1;
$$;

revoke all on function public.resolve_soccer_manager_team(bigint,text) from public, anon;
grant execute on function public.resolve_soccer_manager_team(bigint,text) to authenticated, service_role;

-- Seed explicit Soccer Manager aliases from approved Manager Portal claims. Resolve
-- the club recorded by the claim itself; never infer it from the manager's current
-- game-world assignment, which may have changed since the claim was approved.
insert into public.soccer_manager_team_aliases(game_world_id, source_name, source_key, team_id, source)
select distinct on (c.game_world_id, public.team_directory_key(c.claimed_club_name))
  c.game_world_id,
  c.claimed_club_name,
  public.team_directory_key(c.claimed_club_name),
  t.id,
  'approved_manager_claim'
from public.manager_portal_claims c
join public.teams t
  on public.team_directory_key(t.name) = public.team_directory_key(c.claimed_club_name)
where c.status = 'approved'
  and nullif(trim(c.claimed_club_name), '') is not null
  and exists (
    select 1
    from public.game_world_clubs g
    where g.game_world_id = c.game_world_id
      and public.team_directory_key(g.club_name) = public.team_directory_key(c.claimed_club_name)
  )
order by c.game_world_id,
         public.team_directory_key(c.claimed_club_name),
         c.reviewed_at desc nulls last,
         c.id desc
on conflict (game_world_id, source_key) do update set
  source_name = excluded.source_name,
  team_id = excluded.team_id,
  source = excluded.source,
  updated_at = now();

-- Manager Lab club directory now emits canonical Top 100 names where resolvable,
-- while retaining the raw SM label for audit/debugging. Archived team IDs are the
-- authoritative identity whenever the importer already resolved them; name-based
-- resolution is only a fallback for snapshots whose team ID is still null.
create or replace function public.manager_lab_clubs(target_setup_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  setup_id text := nullif(trim(target_setup_id), '');
  v_world_id bigint;
  result jsonb;
begin
  if auth.uid() is null or not public.is_admin() then raise exception 'Global admin access required'; end if;
  if setup_id is null or setup_id !~ '^[0-9]+$' then raise exception 'Soccer Manager setup id must be numeric'; end if;

  select id into v_world_id from public.game_worlds
  where external_world_id = setup_id::bigint order by id limit 1;
  if v_world_id is null then raise exception 'No archived Soccer Manager world %', setup_id; end if;

  with latest as (
    select distinct on (s.source_fixture_id) s.*
    from public.soccer_manager_match_snapshots s
    where s.game_world_id = v_world_id
    order by s.source_fixture_id, s.source_version desc
  ), appearances as (
    select home_source_club_id source_club_id, home_name raw_name, home_team_id archived_team_id, source_fixture_id from latest
    union all
    select away_source_club_id, away_name, away_team_id, source_fixture_id from latest
  ), clubs as (
    select
      source_club_id,
      max(raw_name) raw_name,
      (array_agg(archived_team_id order by source_fixture_id desc) filter (where archived_team_id is not null))[1] archived_team_id,
      count(distinct source_fixture_id)::integer match_count
    from appearances
    where nullif(trim(source_club_id), '') is not null
    group by source_club_id
  ), resolved as (
    select
      c.source_club_id,
      c.raw_name,
      c.match_count,
      coalesce(c.archived_team_id, r.team_id) team_id,
      coalesce(t.name, r.canonical_name, c.raw_name, c.source_club_id) canonical_name,
      case
        when c.archived_team_id is not null then 'archived_team_id'
        else coalesce(r.resolution, 'raw_source_name')
      end resolution
    from clubs c
    left join public.teams t on t.id = c.archived_team_id
    left join lateral public.resolve_soccer_manager_team(v_world_id, c.raw_name) r
      on c.archived_team_id is null
  )
  select jsonb_build_object(
    'setupId', setup_id,
    'clubs', coalesce(jsonb_agg(jsonb_build_object(
      'sourceClubId', source_club_id,
      'teamId', team_id,
      'name', canonical_name,
      'rawName', raw_name,
      'resolution', resolution,
      'matchCount', match_count
    ) order by lower(canonical_name)), '[]'::jsonb)
  ) into result
  from resolved;

  return result;
end;
$$;

revoke all on function public.manager_lab_clubs(text) from public, anon;
grant execute on function public.manager_lab_clubs(text) to authenticated, service_role;
