-- Canonical game-world directories, guest registration support, and game-world-aware portal claims.

alter table public.game_worlds
  add column if not exists external_world_id bigint;

create unique index if not exists game_worlds_external_world_id_uidx
  on public.game_worlds(external_world_id)
  where external_world_id is not null;

update public.game_worlds set external_world_id = 239138 where slug = 'top-100' and external_world_id is distinct from 239138;
update public.game_worlds set external_world_id = 466578 where slug = 'regen' and external_world_id is distinct from 466578;

insert into public.competition_types(name, slug)
select 'Regen Tournament', 'regen-tournament'
where not exists (select 1 from public.competition_types where slug = 'regen-tournament');

create table if not exists public.game_world_clubs (
  id bigint generated by default as identity primary key,
  game_world_id bigint not null references public.game_worlds(id) on delete cascade,
  club_name text not null,
  club_key text not null,
  current_manager_name text,
  manager_key text,
  occupied boolean not null default true,
  division integer check (division between 1 and 5),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(game_world_id, club_key)
);

create index if not exists game_world_clubs_world_occupied_idx
  on public.game_world_clubs(game_world_id, occupied, active, club_name);
create index if not exists game_world_clubs_world_manager_idx
  on public.game_world_clubs(game_world_id, manager_key)
  where manager_key is not null;

alter table public.game_world_clubs enable row level security;
grant select on public.game_world_clubs to anon, authenticated;
grant select, insert, update, delete on public.game_world_clubs to service_role;

drop policy if exists "Public read active game world clubs" on public.game_world_clubs;
create policy "Public read active game world clubs"
  on public.game_world_clubs for select
  to anon, authenticated
  using (active = true);

drop policy if exists "Platform admins manage game world clubs" on public.game_world_clubs;
create policy "Platform admins manage game world clubs"
  on public.game_world_clubs for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

alter table public.manager_portal_claims
  add column if not exists game_world_id bigint references public.game_worlds(id) on delete restrict;
alter table public.manager_portal_accounts
  add column if not exists game_world_id bigint references public.game_worlds(id) on delete restrict;

create index if not exists manager_portal_claims_game_world_idx on public.manager_portal_claims(game_world_id);
create index if not exists manager_portal_accounts_game_world_idx on public.manager_portal_accounts(game_world_id);

-- Existing Portal identities pre-date multi-world claims and belong to the original Top 100 workflow.
update public.manager_portal_accounts
set game_world_id = (select id from public.game_worlds where slug = 'top-100')
where game_world_id is null;
update public.manager_portal_claims
set game_world_id = (select id from public.game_worlds where slug = 'top-100')
where game_world_id is null;

alter table public.manager_portal_accounts alter column game_world_id set not null;
alter table public.manager_portal_claims alter column game_world_id set not null;

-- Ratings are mandatory for every new registration. Older rows may legitimately
-- pre-date that rule, so preserve legacy NULLs rather than inventing a rating.
-- Existing 65-95 values remain valid; the trigger below requires every new/edited
-- registration to provide a whole-number rating in that range.
alter table public.tournament_registrations
  drop constraint if exists tournament_registrations_rating_range;
alter table public.tournament_registrations
  add constraint tournament_registrations_rating_range
    check (rating is null or (rating between 65 and 95 and rating = trunc(rating)));

-- Central registration guard: old clients, RPCs and service-side callers must all use
-- a club/manager pairing from the tournament's current game-world directory.
create or replace function public.validate_tournament_registration_directory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_game_world_id bigint;
  club_row public.game_world_clubs%rowtype;
begin
  if new.rating is null or new.rating < 65 or new.rating > 95 or new.rating <> trunc(new.rating) then
    raise exception 'Choose an average team rating from 65 to 95';
  end if;

  select t.game_world_id into target_game_world_id
  from public.tournaments t
  where t.id = new.tournament_id;

  if target_game_world_id is null then
    raise exception 'Tournament has no game world';
  end if;

  select * into club_row
  from public.game_world_clubs c
  where c.game_world_id = target_game_world_id
    and c.club_key = public.normal_registration_key(new.club_name)
    and c.active = true
    and c.occupied = true
  limit 1;

  if not found then
    raise exception 'Choose a currently managed club from this game world';
  end if;

  if club_row.manager_key is null
     or club_row.manager_key <> public.normal_registration_key(new.manager_name) then
    raise exception '% is currently listed as managed by %', club_row.club_name, club_row.current_manager_name;
  end if;

  new.club_name := club_row.club_name;
  new.club_key := club_row.club_key;
  new.manager_name := club_row.current_manager_name;
  new.manager_key := club_row.manager_key;
  return new;
end;
$$;

revoke all on function public.validate_tournament_registration_directory() from public, anon, authenticated;

drop trigger if exists tournament_registration_directory_guard on public.tournament_registrations;
create trigger tournament_registration_directory_guard
before insert or update of tournament_id, manager_name, club_name, manager_key, club_key, rating
on public.tournament_registrations
for each row execute function public.validate_tournament_registration_directory();

-- Portal claims use the same directory and record a canonical manager suggestion where possible.
create or replace function public.validate_manager_portal_claim_directory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  club_row public.game_world_clubs%rowtype;
  resolved_manager_id bigint;
begin
  if new.game_world_id is null then
    raise exception 'Choose your game world';
  end if;

  select * into club_row
  from public.game_world_clubs c
  where c.game_world_id = new.game_world_id
    and c.club_key = public.normal_registration_key(new.claimed_club_name)
    and c.active = true
    and c.occupied = true
  limit 1;

  if not found then
    raise exception 'Choose a currently managed club from this game world';
  end if;

  if club_row.manager_key is null
     or club_row.manager_key <> public.normal_registration_key(new.claimed_manager_name) then
    raise exception 'That manager does not match the current manager listed for this club';
  end if;

  select m.id into resolved_manager_id
  from public.managers m
  where public.normal_registration_key(coalesce(m.display_name, m.name)) = club_row.manager_key
  order by m.active desc, m.id
  limit 1;

  new.claimed_club_name := club_row.club_name;
  new.claimed_manager_name := club_row.current_manager_name;
  if resolved_manager_id is not null then
    new.suggested_manager_id := resolved_manager_id;
  end if;
  return new;
end;
$$;

revoke all on function public.validate_manager_portal_claim_directory() from public, anon, authenticated;

drop trigger if exists manager_portal_claim_directory_guard on public.manager_portal_claims;
create trigger manager_portal_claim_directory_guard
before insert or update of game_world_id, claimed_club_name, claimed_manager_name
on public.manager_portal_claims
for each row execute function public.validate_manager_portal_claim_directory();

create or replace function public.approve_manager_portal_claim(
  target_claim_id bigint,
  target_manager_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  claim_row public.manager_portal_claims%rowtype;
  resolved_manager_id bigint;
  reviewer_label text;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  select * into claim_row from public.manager_portal_claims where id = target_claim_id for update;
  if not found then raise exception 'Manager claim not found'; end if;
  if claim_row.status <> 'pending' then raise exception 'Manager claim has already been reviewed'; end if;

  resolved_manager_id := coalesce(target_manager_id, claim_row.suggested_manager_id);
  if resolved_manager_id is null then
    select m.id into resolved_manager_id
    from public.managers m
    where public.normal_registration_key(coalesce(m.display_name, m.name)) = public.normal_registration_key(claim_row.claimed_manager_name)
    order by m.active desc, m.id
    limit 1;
  end if;
  if resolved_manager_id is null then raise exception 'Choose a manager before approving this claim'; end if;

  reviewer_label := coalesce(
    nullif(auth.jwt() ->> 'name', ''),
    nullif(auth.jwt() -> 'user_metadata' ->> 'full_name', ''),
    nullif(auth.jwt() ->> 'email', ''),
    'Administrator'
  );

  insert into public.manager_portal_accounts(auth_user_id, manager_id, game_world_id, email, active, updated_at)
  values (claim_row.auth_user_id, resolved_manager_id, claim_row.game_world_id, claim_row.email, true, now())
  on conflict (auth_user_id) do update set
    manager_id = excluded.manager_id,
    game_world_id = excluded.game_world_id,
    email = excluded.email,
    active = true,
    updated_at = now();

  update public.manager_portal_claims set
    suggested_manager_id = resolved_manager_id,
    status = 'approved',
    reviewed_by = auth.uid(),
    reviewed_by_label = reviewer_label,
    reviewed_at = now(),
    updated_at = now()
  where id = target_claim_id;

  -- Guest registrations need no email. A later approved Portal claim can attach the
  -- historic registration by canonical manager + club + game world.
  update public.tournament_registrations r
  set auth_user_id = claim_row.auth_user_id,
      manager_id = resolved_manager_id,
      updated_at = now()
  from public.tournaments t
  where r.tournament_id = t.id
    and t.game_world_id = claim_row.game_world_id
    and r.auth_user_id is null
    and r.manager_key = public.normal_registration_key(claim_row.claimed_manager_name)
    and r.club_key = public.normal_registration_key(claim_row.claimed_club_name);

  return resolved_manager_id;
end;
$$;

revoke all on function public.approve_manager_portal_claim(bigint,bigint) from public, anon;
grant execute on function public.approve_manager_portal_claim(bigint,bigint) to authenticated;

-- Create Regen S4 with registration open before the final field or tournament shape is known.
insert into public.tournaments(
  name, status, format, source, max_entries, actual_entries, group_count, teams_per_group,
  knockout_teams, game_world_id, competition_type_id, season_number, slug, public_slug,
  is_public, registration_status, archive_quality
)
select
  'Top 100 Regen S4', 'draft', 'TBC', 'manual', null, 0, null, null,
  null, gw.id, ct.id, 4, 'top-100-regen-s4', 's4', true, 'open', 'complete'
from public.game_worlds gw
join public.competition_types ct on ct.slug = 'regen-tournament'
where gw.slug = 'regen'
  and not exists (
    select 1 from public.tournaments t
    where t.game_world_id = gw.id and t.competition_type_id = ct.id and t.season_number = 4
  );
