create table if not exists public.manager_reminder_preferences (
  account_id bigint primary key references public.manager_portal_accounts(id) on delete cascade,
  youth_cup_enabled boolean not null default false,
  fixture_assigned boolean not null default true,
  day_before boolean not null default true,
  deadline_day boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.manager_reminder_deliveries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.manager_portal_accounts(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('fixture_assigned', 'day_before', 'deadline_day')),
  sent_at timestamptz not null default now(),
  delivery_key text not null unique,
  provider_message_id text,
  error text
);

alter table public.manager_reminder_preferences enable row level security;
alter table public.manager_reminder_deliveries enable row level security;

drop policy if exists "Managers read own reminder preferences" on public.manager_reminder_preferences;
create policy "Managers read own reminder preferences"
  on public.manager_reminder_preferences for select to authenticated
  using (exists (
    select 1 from public.manager_portal_accounts a
    where a.id = account_id and a.auth_user_id = auth.uid() and a.active = true
  ));

drop policy if exists "Managers insert own reminder preferences" on public.manager_reminder_preferences;
create policy "Managers insert own reminder preferences"
  on public.manager_reminder_preferences for insert to authenticated
  with check (exists (
    select 1 from public.manager_portal_accounts a
    where a.id = account_id and a.auth_user_id = auth.uid() and a.active = true
  ));

drop policy if exists "Managers update own reminder preferences" on public.manager_reminder_preferences;
create policy "Managers update own reminder preferences"
  on public.manager_reminder_preferences for update to authenticated
  using (exists (
    select 1 from public.manager_portal_accounts a
    where a.id = account_id and a.auth_user_id = auth.uid() and a.active = true
  ))
  with check (exists (
    select 1 from public.manager_portal_accounts a
    where a.id = account_id and a.auth_user_id = auth.uid() and a.active = true
  ));

drop policy if exists "Managers read own reminder deliveries" on public.manager_reminder_deliveries;
create policy "Managers read own reminder deliveries"
  on public.manager_reminder_deliveries for select to authenticated
  using (exists (
    select 1 from public.manager_portal_accounts a
    where a.id = account_id and a.auth_user_id = auth.uid() and a.active = true
  ));

comment on table public.manager_reminder_preferences is 'Opt-in notification preferences tied to an approved Manager Portal account.';
comment on table public.manager_reminder_deliveries is 'Idempotency/audit log for manager reminder emails.';
