-- Ranked manager-account claim suggestions and learned team aliases.
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.manager_team_aliases (
  id bigint generated by default as identity primary key,
  alias text not null,
  alias_key text not null unique,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_from_claim_id bigint references public.manager_portal_claims(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.manager_team_aliases enable row level security;
create policy "Admins can manage manager team aliases"
  on public.manager_team_aliases for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create or replace function public.manager_portal_claim_suggestions(target_claim_id bigint)
returns table (
  manager_id bigint,
  manager_name text,
  team_id bigint,
  team_name text,
  latest_season integer,
  seed integer,
  group_code text,
  score integer,
  confidence text,
  reasons text[]
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  with claim as (
    select
      c.claimed_manager_name,
      c.claimed_club_name,
      public.normalise_manager_claim_text(c.claimed_manager_name) as claim_manager_key,
      public.canonical_manager_claim_club(c.claimed_club_name) as claim_club_key,
      public.normalise_manager_claim_text(c.claimed_club_name) as claim_club_raw
    from public.manager_portal_claims c
    where c.id = target_claim_id and public.is_admin()
  ),
  candidates as (
    select
      te.manager_id,
      coalesce(m.display_name, m.name) as manager_name,
      te.team_id,
      t.name as team_name,
      coalesce(tr.season_number, 0) as latest_season,
      te.seed,
      te.group_code,
      public.normalise_manager_claim_text(coalesce(m.display_name, m.name)) as manager_key,
      public.canonical_manager_claim_club(t.name) as team_key,
      public.normalise_manager_claim_text(t.name) as team_raw,
      exists (
        select 1 from public.manager_team_aliases a
        where a.team_id = te.team_id and a.alias_key = cl.claim_club_raw
      ) as alias_exact,
      similarity(public.normalise_manager_claim_text(coalesce(m.display_name, m.name)), cl.claim_manager_key) as manager_similarity,
      greatest(
        similarity(public.canonical_manager_claim_club(t.name), cl.claim_club_key),
        similarity(public.normalise_manager_claim_text(t.name), cl.claim_club_raw)
      ) as club_similarity,
      cl.claim_manager_key,
      cl.claim_club_key
    from public.tournament_entries te
    join public.managers m on m.id = te.manager_id
    join public.teams t on t.id = te.team_id
    join public.tournaments tr on tr.id = te.tournament_id
    cross join claim cl
  ),
  scored as (
    select *,
      (case when manager_key = claim_manager_key then 55
             when manager_key like claim_manager_key || ' %' then 45
             else round(manager_similarity * 38)::int end)
      + (case when alias_exact then 42
              when team_key = claim_club_key then 38
              else round(club_similarity * 34)::int end) as total_score
    from candidates
    where (manager_key = claim_manager_key or manager_key like claim_manager_key || ' %' or manager_similarity >= 0.28)
      and (alias_exact or team_key = claim_club_key or club_similarity >= 0.28)
  ),
  deduped as (
    select distinct on (manager_id, team_id) *
    from scored
    order by manager_id, team_id, total_score desc, latest_season desc
  )
  select
    d.manager_id,
    d.manager_name,
    d.team_id,
    d.team_name,
    d.latest_season,
    d.seed,
    d.group_code,
    least(d.total_score, 100) as score,
    case when d.total_score >= 92 then 'Very strong'
         when d.total_score >= 78 then 'Likely'
         else 'Possible' end as confidence,
    array_remove(array[
      case when d.manager_key = d.claim_manager_key then 'Exact manager name' end,
      case when d.manager_key like d.claim_manager_key || ' %' and d.manager_key <> d.claim_manager_key then 'Shortened manager name' end,
      case when d.alias_exact then 'Known club alias' end,
      case when d.team_key = d.claim_club_key and not d.alias_exact then 'Matching club name' end,
      case when d.team_key <> d.claim_club_key and not d.alias_exact then 'Similar club name' end
    ], null) as reasons
  from deduped d
  order by d.total_score desc, d.latest_season desc, d.seed asc nulls last
  limit 6;
$$;

create or replace function public.approve_manager_portal_claim_with_alias(
  target_claim_id bigint,
  target_manager_id bigint,
  target_team_id bigint default null,
  remember_team_alias boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  claim_row public.manager_portal_claims%rowtype;
  canonical_team_name text;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  select * into claim_row from public.manager_portal_claims
  where id = target_claim_id for update;
  if not found then raise exception 'Manager claim not found'; end if;

  perform public.approve_manager_portal_claim(target_claim_id, target_manager_id);

  if remember_team_alias and target_team_id is not null then
    select name into canonical_team_name from public.teams where id = target_team_id;
    if canonical_team_name is null then raise exception 'Team not found'; end if;

    if public.normalise_manager_claim_text(claim_row.claimed_club_name)
       <> public.normalise_manager_claim_text(canonical_team_name) then
      insert into public.manager_team_aliases(alias, alias_key, team_id, created_from_claim_id, created_by)
      values (
        claim_row.claimed_club_name,
        public.normalise_manager_claim_text(claim_row.claimed_club_name),
        target_team_id,
        target_claim_id,
        auth.uid()
      )
      on conflict (alias_key) do update set
        alias = excluded.alias,
        team_id = excluded.team_id,
        created_from_claim_id = excluded.created_from_claim_id,
        created_by = excluded.created_by,
        updated_at = now();
    end if;
  end if;

  return target_manager_id;
end;
$$;

-- Include learned aliases in future exact automatic matches.
create or replace function public.find_manager_portal_claim_match(
  claimed_manager_name text,
  claimed_club_name text
)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  with candidates as (
    select distinct te.manager_id
    from public.tournament_entries te
    join public.managers m on m.id = te.manager_id
    join public.teams t on t.id = te.team_id
    where public.normalise_manager_claim_text(coalesce(m.display_name, m.name))
          = public.normalise_manager_claim_text(claimed_manager_name)
      and (
        public.canonical_manager_claim_club(t.name) = public.canonical_manager_claim_club(claimed_club_name)
        or exists (
          select 1 from public.manager_team_aliases a
          where a.team_id = te.team_id
            and a.alias_key = public.normalise_manager_claim_text(claimed_club_name)
        )
      )
  )
  select case when count(*) = 1 then min(manager_id) else null end from candidates;
$$;

grant execute on function public.manager_portal_claim_suggestions(bigint) to authenticated;
grant execute on function public.approve_manager_portal_claim_with_alias(bigint, bigint, bigint, boolean) to authenticated;
grant execute on function public.find_manager_portal_claim_match(text, text) to authenticated;

update public.manager_portal_claims
set suggested_manager_id = public.find_manager_portal_claim_match(claimed_manager_name, claimed_club_name)
where status = 'pending';
