-- Central manager lifecycle controls for Manager Portal, Voting and Awards.
-- Managers are never deleted: historical identities remain intact.

create table if not exists public.manager_game_world_memberships (
  manager_id bigint not null references public.managers(id) on delete restrict,
  game_world_id bigint not null references public.game_worlds(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (manager_id, game_world_id)
);

alter table public.manager_game_world_memberships enable row level security;

drop policy if exists "Admins can read manager game world memberships" on public.manager_game_world_memberships;
create policy "Admins can read manager game world memberships"
  on public.manager_game_world_memberships for select to authenticated
  using (public.is_admin());

-- Backfill memberships from the existing Portal accounts.
insert into public.manager_game_world_memberships(manager_id, game_world_id, active)
select distinct a.manager_id, a.game_world_id, coalesce(a.active, false)
from public.manager_portal_accounts a
where a.manager_id is not null and a.game_world_id is not null
on conflict (manager_id, game_world_id) do update
set active = excluded.active,
    updated_at = now();

-- Also backfill managers who are present in a game-world club directory but
-- have not yet claimed a Portal account.
insert into public.manager_game_world_memberships(manager_id, game_world_id, active)
select distinct m.id, c.game_world_id, true
from public.game_world_clubs c
join public.managers m
  on public.normal_registration_key(coalesce(m.display_name, m.name)) = c.manager_key
where c.active = true
  and c.occupied = true
  and c.manager_key is not null
on conflict (manager_id, game_world_id) do nothing;

create table if not exists public.manager_lifecycle_audit (
  id bigint generated by default as identity primary key,
  manager_id bigint not null references public.managers(id) on delete restrict,
  game_world_id bigint not null references public.game_worlds(id) on delete restrict,
  action text not null check (action in ('created','activated','deactivated')),
  reason text,
  performed_by uuid not null,
  created_at timestamptz not null default now()
);

alter table public.manager_lifecycle_audit enable row level security;

drop policy if exists "Admins can read manager lifecycle audit" on public.manager_lifecycle_audit;
create policy "Admins can read manager lifecycle audit"
  on public.manager_lifecycle_audit for select to authenticated
  using (public.is_admin());

-- Prevent a later Top 100 account claim/approval from accidentally re-enabling
-- Portal, Voting or Awards access for a manager who is inactive in Top 100.
create or replace function public.enforce_active_manager_portal_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  world_slug text;
  membership_is_active boolean;
begin
  if not coalesce(new.active, false) then
    return new;
  end if;

  select slug into world_slug from public.game_worlds where id = new.game_world_id;

  if world_slug = 'top-100' then
    select gm.active into membership_is_active
    from public.manager_game_world_memberships gm
    where gm.manager_id = new.manager_id
      and gm.game_world_id = new.game_world_id;

    if not coalesce(membership_is_active, false) then
      raise exception 'This manager is inactive in Top 100. Reactivate them before enabling their account.';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_active_manager_portal_account() from public, anon, authenticated;

drop trigger if exists manager_portal_account_requires_active_manager on public.manager_portal_accounts;
create trigger manager_portal_account_requires_active_manager
before insert or update of manager_id, game_world_id, active
on public.manager_portal_accounts
for each row execute function public.enforce_active_manager_portal_account();

create or replace function public.admin_list_manager_lifecycle()
returns table (
  manager_id bigint,
  name text,
  display_name text,
  active boolean,
  account_count bigint,
  active_account_count bigint,
  account_emails text[]
)
language plpgsql
security definer
set search_path = public
as $$
declare
  top100_world_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  select id into top100_world_id from public.game_worlds where slug = 'top-100';
  if top100_world_id is null then
    raise exception 'Top 100 game world not found';
  end if;

  return query
  select
    m.id,
    m.name,
    m.display_name,
    gm.active,
    count(a.id),
    count(a.id) filter (where a.active),
    coalesce(array_agg(a.email order by a.email) filter (where a.email is not null), array[]::text[])
  from public.manager_game_world_memberships gm
  join public.managers m on m.id = gm.manager_id
  left join public.manager_portal_accounts a
    on a.manager_id = m.id
   and a.game_world_id = top100_world_id
  where gm.game_world_id = top100_world_id
  group by m.id, m.name, m.display_name, gm.active
  order by coalesce(m.display_name, m.name), m.id;
end;
$$;

create or replace function public.admin_create_manager(
  manager_name text,
  manager_display_name text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := nullif(btrim(manager_name), '');
  clean_display text := nullif(btrim(manager_display_name), '');
  lookup_key text;
  top100_world_id bigint;
  existing_row public.managers%rowtype;
  created_row public.managers%rowtype;
  existing_membership boolean;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;
  if clean_name is null then
    raise exception 'Manager name is required';
  end if;

  clean_display := coalesce(clean_display, clean_name);
  lookup_key := public.normal_registration_key(clean_display);
  select id into top100_world_id from public.game_worlds where slug = 'top-100';
  if top100_world_id is null then
    raise exception 'Top 100 game world not found';
  end if;

  select * into existing_row
  from public.managers m
  where public.normal_registration_key(m.name) = lookup_key
     or public.normal_registration_key(coalesce(m.display_name, m.name)) = lookup_key
  order by m.id
  limit 1;

  if found then
    select gm.active into existing_membership
    from public.manager_game_world_memberships gm
    where gm.manager_id = existing_row.id
      and gm.game_world_id = top100_world_id;

    if existing_membership then
      raise exception 'Manager already exists and is active in Top 100';
    elsif existing_membership is false then
      raise exception 'Manager already exists but is inactive in Top 100; reactivate the existing record instead';
    end if;

    insert into public.manager_game_world_memberships(manager_id, game_world_id, active)
    values (existing_row.id, top100_world_id, true);

    update public.managers set active = true where id = existing_row.id;

    insert into public.manager_lifecycle_audit(manager_id, game_world_id, action, reason, performed_by)
    values (existing_row.id, top100_world_id, 'created', 'Added existing canonical identity to Top 100', auth.uid());

    return existing_row;
  end if;

  insert into public.managers(name, display_name, canonical_name, active)
  values (clean_name, clean_display, lookup_key, true)
  returning * into created_row;

  insert into public.manager_game_world_memberships(manager_id, game_world_id, active)
  values (created_row.id, top100_world_id, true);

  insert into public.manager_lifecycle_audit(manager_id, game_world_id, action, reason, performed_by)
  values (created_row.id, top100_world_id, 'created', 'Created in Top 100 manager lifecycle admin', auth.uid());

  return created_row;
end;
$$;

create or replace function public.admin_set_manager_active(
  target_manager_id bigint,
  target_active boolean,
  reason text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  manager_row public.managers%rowtype;
  clean_reason text := nullif(btrim(reason), '');
  top100_world_id bigint;
  membership_row public.manager_game_world_memberships%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  select id into top100_world_id from public.game_worlds where slug = 'top-100';
  if top100_world_id is null then
    raise exception 'Top 100 game world not found';
  end if;

  select * into manager_row
  from public.managers
  where id = target_manager_id
  for update;
  if not found then
    raise exception 'Manager not found';
  end if;

  select * into membership_row
  from public.manager_game_world_memberships
  where manager_id = target_manager_id
    and game_world_id = top100_world_id
  for update;
  if not found then
    raise exception 'Manager is not a Top 100 member';
  end if;

  if membership_row.active = target_active then
    return manager_row;
  end if;

  if not target_active then
    -- Disable Top 100 Portal access first.
    update public.manager_portal_accounts
    set active = false,
        updated_at = now()
    where manager_id = target_manager_id
      and game_world_id = top100_world_id;

    -- Also revoke delegated organiser/assistant access immediately. Those roles
    -- are intentionally not restored automatically if the manager later returns.
    update public.tournament_organisers o
    set active = false,
        updated_at = now()
    where o.active = true
      and exists (
        select 1
        from public.manager_portal_accounts a
        join public.tournaments t on t.id = o.tournament_id
        where a.auth_user_id = o.auth_user_id
          and a.manager_id = target_manager_id
          and a.game_world_id = top100_world_id
          and t.game_world_id = top100_world_id
      );
  end if;

  update public.manager_game_world_memberships
  set active = target_active,
      updated_at = now()
  where manager_id = target_manager_id
    and game_world_id = top100_world_id;

  if target_active then
    update public.managers set active = true where id = target_manager_id;
    update public.manager_portal_accounts
    set active = true,
        updated_at = now()
    where manager_id = target_manager_id
      and game_world_id = top100_world_id;
  elsif not exists (
    select 1 from public.manager_game_world_memberships gm
    where gm.manager_id = target_manager_id and gm.active = true
  ) then
    update public.managers set active = false where id = target_manager_id;
  end if;

  select * into manager_row from public.managers where id = target_manager_id;

  insert into public.manager_lifecycle_audit(manager_id, game_world_id, action, reason, performed_by)
  values (
    target_manager_id,
    top100_world_id,
    case when target_active then 'activated' else 'deactivated' end,
    clean_reason,
    auth.uid()
  );

  -- Deliberately do not alter voting_electorate rows. Open polls retain their
  -- frozen electorate; any exceptional correction remains an explicit audited
  -- voting action rather than a side effect of manager administration.
  return manager_row;
end;
$$;

-- Future Top 100 polls/Awards snapshot only active Top 100 memberships, not
-- global manager identities or accounts belonging solely to other game worlds.
create or replace function public.open_voting_event(target_event_id bigint)
returns integer language plpgsql security definer set search_path = public as $$
declare
  electorate_count integer;
  v_event public.voting_events%rowtype;
  top100_world_id bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into v_event from public.voting_events where id = target_event_id for update;
  if not found then raise exception 'Voting event not found'; end if;
  if v_event.status <> 'draft' then raise exception 'Only draft voting events can be opened'; end if;
  if v_event.closes_at is null or v_event.closes_at <= now() then raise exception 'Set a future closing time before opening the vote'; end if;

  select id into top100_world_id from public.game_worlds where slug = 'top-100';
  if top100_world_id is null then raise exception 'Top 100 game world not found'; end if;

  delete from public.voting_electorate where event_id = target_event_id;
  insert into public.voting_electorate(event_id, manager_id, manager_account_id, manager_name)
  select target_event_id, a.manager_id, a.id, coalesce(nullif(m.display_name, ''), m.name)
  from public.manager_portal_accounts a
  join public.managers m on m.id = a.manager_id
  join public.manager_game_world_memberships gm
    on gm.manager_id = a.manager_id
   and gm.game_world_id = top100_world_id
   and gm.active = true
  where a.active = true
    and a.game_world_id = top100_world_id;
  get diagnostics electorate_count = row_count;
  if electorate_count = 0 then raise exception 'No active Top 100 manager accounts are available for the electorate'; end if;

  update public.voting_events set status = 'open', opens_at = coalesce(opens_at, now()), updated_at = now() where id = target_event_id;
  insert into public.voting_audit_log(event_id, actor_user_id, action, details)
  values (target_event_id, auth.uid(), 'event_opened', jsonb_build_object('electorate_count', electorate_count, 'game_world', 'top-100'));
  return electorate_count;
end $$;

revoke all on function public.admin_list_manager_lifecycle() from public;
revoke all on function public.admin_create_manager(text,text) from public;
revoke all on function public.admin_set_manager_active(bigint,boolean,text) from public;
revoke all on function public.open_voting_event(bigint) from public;
grant execute on function public.admin_list_manager_lifecycle() to authenticated;
grant execute on function public.admin_create_manager(text,text) to authenticated;
grant execute on function public.admin_set_manager_active(bigint,boolean,text) to authenticated;
grant execute on function public.open_voting_event(bigint) to authenticated;
