-- Central manager lifecycle controls for Manager Portal, Voting and Awards.
-- Managers are never deleted: historical identities remain intact.

create table if not exists public.manager_lifecycle_audit (
  id bigint generated by default as identity primary key,
  manager_id bigint not null references public.managers(id) on delete restrict,
  action text not null check (action in ('created','activated','deactivated')),
  reason text,
  performed_by uuid not null,
  created_at timestamptz not null default now()
);

alter table public.manager_lifecycle_audit enable row level security;

drop policy if exists "Admins can read manager lifecycle audit" on public.manager_lifecycle_audit;
create policy "Admins can read manager lifecycle audit"
  on public.manager_lifecycle_audit for select to authenticated
  using (public.is_admin());

-- Prevent a later account claim/approval from accidentally re-enabling Portal,
-- Voting or Awards access for a manager who has been marked inactive.
create or replace function public.enforce_active_manager_portal_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  manager_is_active boolean;
begin
  if coalesce(new.active, false) then
    select coalesce(m.active, false) into manager_is_active
    from public.managers m
    where m.id = new.manager_id;

    if not coalesce(manager_is_active, false) then
      raise exception 'This manager is inactive. Reactivate the canonical manager record before enabling their account.';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_active_manager_portal_account() from public, anon, authenticated;

drop trigger if exists manager_portal_account_requires_active_manager on public.manager_portal_accounts;
create trigger manager_portal_account_requires_active_manager
before insert or update of manager_id, active
on public.manager_portal_accounts
for each row execute function public.enforce_active_manager_portal_account();

create or replace function public.admin_list_manager_lifecycle()
returns table (
  manager_id bigint,
  name text,
  display_name text,
  active boolean,
  account_count bigint,
  active_account_count bigint,
  account_emails text[]
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select
    m.id,
    m.name,
    m.display_name,
    coalesce(m.active, false),
    count(a.id),
    count(a.id) filter (where a.active),
    coalesce(array_agg(a.email order by a.email) filter (where a.email is not null), array[]::text[])
  from public.managers m
  left join public.manager_portal_accounts a on a.manager_id = m.id
  group by m.id, m.name, m.display_name, m.active
  order by coalesce(m.display_name, m.name), m.id;
end;
$$;

create or replace function public.admin_create_manager(
  manager_name text,
  manager_display_name text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := nullif(btrim(manager_name), '');
  clean_display text := nullif(btrim(manager_display_name), '');
  existing_row public.managers%rowtype;
  created_row public.managers%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;
  if clean_name is null then
    raise exception 'Manager name is required';
  end if;

  select * into existing_row
  from public.managers
  where lower(btrim(name)) = lower(clean_name)
  order by id
  limit 1;

  if found then
    if existing_row.active then
      raise exception 'Manager already exists and is active';
    end if;
    raise exception 'Manager already exists but is inactive; reactivate the existing record instead';
  end if;

  insert into public.managers(name, display_name, canonical_name, active)
  values (clean_name, coalesce(clean_display, clean_name), lower(clean_name), true)
  returning * into created_row;

  insert into public.manager_lifecycle_audit(manager_id, action, reason, performed_by)
  values (created_row.id, 'created', 'Created in manager lifecycle admin', auth.uid());

  return created_row;
end;
$$;

create or replace function public.admin_set_manager_active(
  target_manager_id bigint,
  target_active boolean,
  reason text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  manager_row public.managers%rowtype;
  clean_reason text := nullif(btrim(reason), '');
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  select * into manager_row
  from public.managers
  where id = target_manager_id
  for update;

  if not found then
    raise exception 'Manager not found';
  end if;

  if manager_row.active = target_active then
    return manager_row;
  end if;

  -- When deactivating, switch linked accounts off first so the trigger above
  -- never permits a stale active account. When reactivating, flip the manager
  -- first and then restore any existing linked account.
  if not target_active then
    update public.manager_portal_accounts
    set active = false,
        updated_at = now()
    where manager_id = target_manager_id;
  end if;

  update public.managers
  set active = target_active
  where id = target_manager_id
  returning * into manager_row;

  if target_active then
    update public.manager_portal_accounts
    set active = true,
        updated_at = now()
    where manager_id = target_manager_id;
  end if;

  insert into public.manager_lifecycle_audit(manager_id, action, reason, performed_by)
  values (
    target_manager_id,
    case when target_active then 'activated' else 'deactivated' end,
    clean_reason,
    auth.uid()
  );

  -- Deliberately do not alter voting_electorate rows. Open polls retain their
  -- frozen electorate; any exceptional correction remains an explicit audited
  -- voting action rather than a side effect of manager administration.
  return manager_row;
end;
$$;

revoke all on function public.admin_list_manager_lifecycle() from public;
revoke all on function public.admin_create_manager(text,text) from public;
revoke all on function public.admin_set_manager_active(bigint,boolean,text) from public;
grant execute on function public.admin_list_manager_lifecycle() to authenticated;
grant execute on function public.admin_create_manager(text,text) to authenticated;
grant execute on function public.admin_set_manager_active(bigint,boolean,text) to authenticated;
