create table if not exists public.manager_portal_claims (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  claimed_manager_name text not null,
  claimed_club_name text not null,
  suggested_manager_id bigint references public.managers(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_notes text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.manager_portal_claims enable row level security;

create policy "Users can read their own manager claim"
  on public.manager_portal_claims for select to authenticated
  using (auth.uid() = auth_user_id);

create policy "Users can create their own manager claim"
  on public.manager_portal_claims for insert to authenticated
  with check (auth.uid() = auth_user_id and lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

create policy "Users can update their pending manager claim"
  on public.manager_portal_claims for update to authenticated
  using (auth.uid() = auth_user_id and status = 'pending')
  with check (auth.uid() = auth_user_id and status = 'pending');

create policy "Admins can manage manager claims"
  on public.manager_portal_claims for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create or replace function public.approve_manager_portal_claim(
  target_claim_id bigint,
  target_manager_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  claim_row public.manager_portal_claims%rowtype;
  resolved_manager_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  select * into claim_row
  from public.manager_portal_claims
  where id = target_claim_id
  for update;

  if not found then raise exception 'Manager claim not found'; end if;
  if claim_row.status <> 'pending' then raise exception 'Manager claim has already been reviewed'; end if;

  resolved_manager_id := coalesce(target_manager_id, claim_row.suggested_manager_id);
  if resolved_manager_id is null then raise exception 'Choose a manager before approving this claim'; end if;

  insert into public.manager_portal_accounts (auth_user_id, manager_id, email, active, updated_at)
  values (claim_row.auth_user_id, resolved_manager_id, claim_row.email, true, now())
  on conflict (auth_user_id) do update set
    manager_id = excluded.manager_id,
    email = excluded.email,
    active = true,
    updated_at = now();

  update public.manager_portal_claims set
    suggested_manager_id = resolved_manager_id,
    status = 'approved',
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where id = target_claim_id;

  return resolved_manager_id;
end;
$$;

create or replace function public.reject_manager_portal_claim(
  target_claim_id bigint,
  notes text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  update public.manager_portal_claims set
    status = 'rejected',
    review_notes = notes,
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where id = target_claim_id and status = 'pending';

  if not found then raise exception 'Pending manager claim not found'; end if;
end;
$$;

grant execute on function public.approve_manager_portal_claim(bigint, bigint) to authenticated;
grant execute on function public.reject_manager_portal_claim(bigint, text) to authenticated;

comment on table public.manager_portal_claims is
  'Self-service claims made after a user verifies their email through Supabase Auth.';
