-- Central manager lifecycle controls for Manager Portal, Voting and Awards.
-- Managers are never deleted: historical identities remain intact.

create table if not exists public.manager_lifecycle_audit (
  id bigint generated by default as identity primary key,
  manager_id bigint not null references public.managers(id) on delete restrict,
  action text not null check (action in ('created','activated','deactivated')),
  reason text,
  performed_by uuid not null,
  created_at timestamptz not null default now()
);

alter table public.manager_lifecycle_audit enable row level security;

drop policy if exists "Admins can read manager lifecycle audit" on public.manager_lifecycle_audit;
create policy "Admins can read manager lifecycle audit"
  on public.manager_lifecycle_audit for select to authenticated
  using (public.is_admin());

create or replace function public.admin_create_manager(
  manager_name text,
  manager_display_name text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := nullif(btrim(manager_name), '');
  clean_display text := nullif(btrim(manager_display_name), '');
  existing_row public.managers%rowtype;
  created_row public.managers%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;
  if clean_name is null then
    raise exception 'Manager name is required';
  end if;

  select * into existing_row
  from public.managers
  where lower(btrim(name)) = lower(clean_name)
  order by id
  limit 1;

  if found then
    if existing_row.active then
      raise exception 'Manager already exists and is active';
    end if;
    raise exception 'Manager already exists but is inactive; reactivate the existing record instead';
  end if;

  insert into public.managers(name, display_name, canonical_name, active)
  values (clean_name, coalesce(clean_display, clean_name), lower(clean_name), true)
  returning * into created_row;

  insert into public.manager_lifecycle_audit(manager_id, action, reason, performed_by)
  values (created_row.id, 'created', 'Created in manager lifecycle admin', auth.uid());

  return created_row;
end;
$$;

create or replace function public.admin_set_manager_active(
  target_manager_id bigint,
  target_active boolean,
  reason text default null
)
returns public.managers
language plpgsql
security definer
set search_path = public
as $$
declare
  manager_row public.managers%rowtype;
  clean_reason text := nullif(btrim(reason), '');
begin
  if not public.is_admin() then
    raise exception 'Admin access required';
  end if;

  select * into manager_row
  from public.managers
  where id = target_manager_id
  for update;

  if not found then
    raise exception 'Manager not found';
  end if;

  if manager_row.active = target_active then
    return manager_row;
  end if;

  update public.managers
  set active = target_active
  where id = target_manager_id
  returning * into manager_row;

  -- Manager Portal, Voting and Awards all resolve identity through active
  -- manager_portal_accounts. Keep account access aligned with manager status.
  update public.manager_portal_accounts
  set active = target_active,
      updated_at = now()
  where manager_id = target_manager_id;

  insert into public.manager_lifecycle_audit(manager_id, action, reason, performed_by)
  values (
    target_manager_id,
    case when target_active then 'activated' else 'deactivated' end,
    clean_reason,
    auth.uid()
  );

  -- Deliberately do not alter voting_electorate rows. Open polls retain their
  -- frozen electorate; any exceptional correction remains an explicit audited
  -- voting action rather than a side effect of manager administration.
  return manager_row;
end;
$$;

revoke all on function public.admin_create_manager(text,text) from public;
revoke all on function public.admin_set_manager_active(bigint,boolean,text) from public;
grant execute on function public.admin_create_manager(text,text) to authenticated;
grant execute on function public.admin_set_manager_active(bigint,boolean,text) to authenticated;
