create table if not exists public.manager_portal_accounts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  manager_id bigint not null unique references public.managers(id) on delete cascade,
  email text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists manager_portal_accounts_email_lower_idx
  on public.manager_portal_accounts (lower(email));

alter table public.manager_portal_accounts enable row level security;

create policy "Managers can read their own portal account"
  on public.manager_portal_accounts
  for select
  to authenticated
  using (auth.uid() = auth_user_id);

create policy "Admins can manage manager portal accounts"
  on public.manager_portal_accounts
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.admin_users
      where admin_users.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.admin_users
      where admin_users.user_id = auth.uid()
    )
  );

comment on table public.manager_portal_accounts is
  'Links a Supabase Auth user to one canonical Top 100 manager for the Manager Portal.';
