-- Shared manager-authenticated voting foundation (V1)
-- Reuses Supabase Auth + manager_portal_accounts as the canonical voter identity.

create table if not exists public.voting_events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  event_type text not null default 'poll' check (event_type in ('poll', 'awards', 'test')),
  status text not null default 'draft' check (status in ('draft', 'open', 'closed', 'cancelled')),
  opens_at timestamptz,
  closes_at timestamptz,
  results_visibility text not null default 'after_close' check (results_visibility in ('hidden', 'after_close', 'live')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint voting_events_close_after_open check (closes_at is null or opens_at is null or closes_at > opens_at)
);

create table if not exists public.voting_questions (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.voting_events(id) on delete cascade,
  title text not null,
  description text,
  question_type text not null check (question_type in ('yes_no', 'single_choice')),
  required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.voting_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.voting_questions(id) on delete cascade,
  label text not null,
  value text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(question_id, label)
);

create table if not exists public.voting_electorate (
  event_id bigint not null references public.voting_events(id) on delete cascade,
  manager_id bigint not null references public.managers(id) on delete restrict,
  manager_account_id bigint references public.manager_portal_accounts(id) on delete set null,
  manager_name text not null,
  included_at timestamptz not null default now(),
  primary key(event_id, manager_id)
);

create table if not exists public.voting_ballots (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.voting_events(id) on delete cascade,
  manager_id bigint not null references public.managers(id) on delete restrict,
  submitted_by uuid not null references auth.users(id) on delete restrict,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, manager_id)
);

create table if not exists public.voting_responses (
  ballot_id bigint not null references public.voting_ballots(id) on delete cascade,
  question_id bigint not null references public.voting_questions(id) on delete cascade,
  option_id bigint not null references public.voting_options(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key(ballot_id, question_id)
);

create table if not exists public.voting_audit_log (
  id bigint generated by default as identity primary key,
  event_id bigint references public.voting_events(id) on delete cascade,
  ballot_id bigint references public.voting_ballots(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  manager_id bigint references public.managers(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists voting_questions_event_idx on public.voting_questions(event_id, sort_order, id);
create index if not exists voting_options_question_idx on public.voting_options(question_id, sort_order, id);
create index if not exists voting_electorate_account_idx on public.voting_electorate(manager_account_id);
create index if not exists voting_responses_question_idx on public.voting_responses(question_id, option_id);
create index if not exists voting_audit_event_idx on public.voting_audit_log(event_id, created_at);

alter table public.voting_events enable row level security;
alter table public.voting_questions enable row level security;
alter table public.voting_options enable row level security;
alter table public.voting_electorate enable row level security;
alter table public.voting_ballots enable row level security;
alter table public.voting_responses enable row level security;
alter table public.voting_audit_log enable row level security;

create policy "Eligible managers can read voting events" on public.voting_events for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.manager_portal_accounts a
    join public.voting_electorate e on e.manager_id = a.manager_id
    where a.auth_user_id = auth.uid() and a.active = true and e.event_id = voting_events.id
  )
);
create policy "Eligible managers can read voting questions" on public.voting_questions for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.manager_portal_accounts a
    join public.voting_electorate e on e.manager_id = a.manager_id
    where a.auth_user_id = auth.uid() and a.active = true and e.event_id = voting_questions.event_id
  )
);
create policy "Eligible managers can read voting options" on public.voting_options for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.voting_questions q
    join public.manager_portal_accounts a on a.auth_user_id = auth.uid() and a.active = true
    join public.voting_electorate e on e.manager_id = a.manager_id and e.event_id = q.event_id
    where q.id = voting_options.question_id
  )
);
create policy "Managers can read their electorate record" on public.voting_electorate for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.manager_portal_accounts a
    where a.auth_user_id = auth.uid() and a.active = true and a.manager_id = voting_electorate.manager_id
  )
);
create policy "Managers can read their own ballots" on public.voting_ballots for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.manager_portal_accounts a
    where a.auth_user_id = auth.uid() and a.active = true and a.manager_id = voting_ballots.manager_id
  )
);
create policy "Managers can read their own responses" on public.voting_responses for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.voting_ballots b
    join public.manager_portal_accounts a on a.manager_id = b.manager_id
    where b.id = voting_responses.ballot_id and a.auth_user_id = auth.uid() and a.active = true
  )
);

create policy "Admins can manage voting events" on public.voting_events for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage voting questions" on public.voting_questions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage voting options" on public.voting_options for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage voting electorate" on public.voting_electorate for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can read voting audit log" on public.voting_audit_log for select to authenticated using (public.is_admin());

create or replace function public.open_voting_event(target_event_id bigint)
returns integer language plpgsql security definer set search_path = public as $$
declare
  electorate_count integer;
  v_event public.voting_events%rowtype;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into v_event from public.voting_events where id = target_event_id for update;
  if not found then raise exception 'Voting event not found'; end if;
  if v_event.status <> 'draft' then raise exception 'Only draft voting events can be opened'; end if;
  if v_event.closes_at is null or v_event.closes_at <= now() then raise exception 'Set a future closing time before opening the vote'; end if;

  delete from public.voting_electorate where event_id = target_event_id;
  insert into public.voting_electorate(event_id, manager_id, manager_account_id, manager_name)
  select target_event_id, a.manager_id, a.id, coalesce(nullif(m.display_name, ''), m.name)
  from public.manager_portal_accounts a join public.managers m on m.id = a.manager_id
  where a.active = true;
  get diagnostics electorate_count = row_count;
  if electorate_count = 0 then raise exception 'No active manager accounts are available for the electorate'; end if;

  update public.voting_events set status = 'open', opens_at = coalesce(opens_at, now()), updated_at = now() where id = target_event_id;
  insert into public.voting_audit_log(event_id, actor_user_id, action, details)
  values (target_event_id, auth.uid(), 'event_opened', jsonb_build_object('electorate_count', electorate_count));
  return electorate_count;
end $$;
grant execute on function public.open_voting_event(bigint) to authenticated;

create or replace function public.close_voting_event(target_event_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.voting_events set status = 'closed', closes_at = least(coalesce(closes_at, now()), now()), updated_at = now()
  where id = target_event_id and status = 'open';
  if not found then raise exception 'Open voting event not found'; end if;
  insert into public.voting_audit_log(event_id, actor_user_id, action) values (target_event_id, auth.uid(), 'event_closed');
end $$;
grant execute on function public.close_voting_event(bigint) to authenticated;

create or replace function public.submit_voting_ballot(target_event_id bigint, answers jsonb)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_account public.manager_portal_accounts%rowtype;
  v_event public.voting_events%rowtype;
  v_ballot_id bigint;
  answer_count integer;
  valid_count integer;
  required_count integer;
  required_answered integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(answers) <> 'array' then raise exception 'Answers must be a JSON array'; end if;

  select * into v_account from public.manager_portal_accounts where auth_user_id = auth.uid() and active = true limit 1;
  if not found then raise exception 'Active manager account required'; end if;
  select * into v_event from public.voting_events where id = target_event_id for update;
  if not found then raise exception 'Voting event not found'; end if;
  if v_event.status <> 'open' then raise exception 'Voting event is not open'; end if;
  if v_event.opens_at is not null and now() < v_event.opens_at then raise exception 'Voting has not opened yet'; end if;
  if v_event.closes_at is not null and now() >= v_event.closes_at then raise exception 'Voting has closed'; end if;
  if not exists (select 1 from public.voting_electorate where event_id = target_event_id and manager_id = v_account.manager_id)
    then raise exception 'Manager is not in this vote''s electorate'; end if;

  with submitted as (
    select distinct (x->>'question_id')::bigint question_id, (x->>'option_id')::bigint option_id
    from jsonb_array_elements(answers) x
  ) select count(*) into answer_count from submitted;
  with submitted as (
    select distinct (x->>'question_id')::bigint question_id, (x->>'option_id')::bigint option_id
    from jsonb_array_elements(answers) x
  ) select count(*) into valid_count from submitted s
    join public.voting_questions q on q.id = s.question_id and q.event_id = target_event_id
    join public.voting_options o on o.id = s.option_id and o.question_id = q.id;
  if answer_count <> valid_count then raise exception 'One or more answers are invalid'; end if;

  select count(*) into required_count from public.voting_questions where event_id = target_event_id and required = true;
  with submitted as (
    select distinct (x->>'question_id')::bigint question_id from jsonb_array_elements(answers) x
  ) select count(*) into required_answered from public.voting_questions q join submitted s on s.question_id = q.id
    where q.event_id = target_event_id and q.required = true;
  if required_answered <> required_count then raise exception 'Please answer every required question'; end if;

  insert into public.voting_ballots(event_id, manager_id, submitted_by, submitted_at, updated_at)
  values (target_event_id, v_account.manager_id, auth.uid(), now(), now())
  on conflict (event_id, manager_id) do update set submitted_by = excluded.submitted_by, updated_at = now()
  returning id into v_ballot_id;

  delete from public.voting_responses where voting_responses.ballot_id = v_ballot_id;
  insert into public.voting_responses(ballot_id, question_id, option_id)
  select v_ballot_id, (x->>'question_id')::bigint, (x->>'option_id')::bigint from jsonb_array_elements(answers) x;
  insert into public.voting_audit_log(event_id, ballot_id, actor_user_id, manager_id, action, details)
  values (target_event_id, v_ballot_id, auth.uid(), v_account.manager_id, 'ballot_submitted', jsonb_build_object('answer_count', answer_count));
  return v_ballot_id;
end $$;
grant execute on function public.submit_voting_ballot(bigint, jsonb) to authenticated;

create or replace function public.get_voting_results(target_event_id bigint)
returns table(question_id bigint, question_title text, option_id bigint, option_label text, votes bigint)
language plpgsql security definer set search_path = public as $$
declare v_event public.voting_events%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_event from public.voting_events where id = target_event_id;
  if not found then raise exception 'Voting event not found'; end if;
  if not public.is_admin() then
    if v_event.results_visibility = 'hidden' then raise exception 'Results are hidden'; end if;
    if v_event.results_visibility = 'after_close' and not (v_event.status = 'closed' or (v_event.closes_at is not null and now() >= v_event.closes_at))
      then raise exception 'Results are not available until voting closes'; end if;
  end if;
  return query
  select q.id, q.title, o.id, o.label, count(r.ballot_id)::bigint
  from public.voting_questions q join public.voting_options o on o.question_id = q.id
  left join public.voting_responses r on r.question_id = q.id and r.option_id = o.id
  where q.event_id = target_event_id
  group by q.id, q.title, q.sort_order, o.id, o.label, o.sort_order
  order by q.sort_order, q.id, o.sort_order, o.id;
end $$;
grant execute on function public.get_voting_results(bigint) to authenticated;

-- Harmless draft test poll. Admin opens it from /vote, which snapshots the electorate.
do $$
declare
  v_event_id bigint;
  v_question_id bigint;
begin
  insert into public.voting_events(slug, title, description, event_type, status, closes_at, results_visibility)
  values ('v1-authenticated-test-poll', 'Top 100 voting system test', 'A harmless test of manager-authenticated one-manager-one-vote polling.', 'test', 'draft', now() + interval '7 days', 'after_close')
  on conflict (slug) do update set updated_at = now()
  returning id into v_event_id;

  if not exists (select 1 from public.voting_questions q where q.event_id = v_event_id) then
    insert into public.voting_questions(event_id, title, question_type, required, sort_order)
    values (v_event_id, 'Did the authenticated voting test work for you?', 'yes_no', true, 1)
    returning id into v_question_id;
    insert into public.voting_options(question_id, label, value, sort_order)
    values (v_question_id, 'Yes', 'yes', 1), (v_question_id, 'No', 'no', 2);
  end if;
end $$;
