-- Manager fixture-arrangement reporting and private evidence.
create table if not exists public.manager_match_arrangements (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  tournament_entry_id bigint references public.tournament_entries(id) on delete set null,
  status text not null check (status in ('sent','received','chased','arranged','problem')),
  reported_at timestamptz not null default now(),
  evidence_path text,
  evidence_name text,
  updated_at timestamptz not null default now(),
  unique (match_id, auth_user_id)
);
alter table public.manager_match_arrangements enable row level security;
drop policy if exists "Managers read own arrangement reports" on public.manager_match_arrangements;
create policy "Managers read own arrangement reports" on public.manager_match_arrangements for select to authenticated using (auth.uid() = auth_user_id);
drop policy if exists "Managers insert own arrangement reports" on public.manager_match_arrangements;
create policy "Managers insert own arrangement reports" on public.manager_match_arrangements for insert to authenticated with check (auth.uid() = auth_user_id);
drop policy if exists "Managers update own arrangement reports" on public.manager_match_arrangements;
create policy "Managers update own arrangement reports" on public.manager_match_arrangements for update to authenticated using (auth.uid() = auth_user_id) with check (auth.uid() = auth_user_id);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('match-evidence','match-evidence',false,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=false,file_size_limit=8388608,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "Managers upload own match evidence" on storage.objects;
create policy "Managers upload own match evidence" on storage.objects for insert to authenticated with check (bucket_id='match-evidence' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "Managers read own match evidence" on storage.objects;
create policy "Managers read own match evidence" on storage.objects for select to authenticated using (bucket_id='match-evidence' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "Managers update own match evidence" on storage.objects;
create policy "Managers update own match evidence" on storage.objects for update to authenticated using (bucket_id='match-evidence' and (storage.foldername(name))[1]=auth.uid()::text);
