-- Manager fixture-arrangement reporting and private evidence.
create table if not exists public.manager_match_arrangements (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  tournament_entry_id bigint references public.tournament_entries(id) on delete set null,
  status text not null check (status in ('sent','received','chased','arranged','problem')),
  reported_at timestamptz not null default now(),
  evidence_path text,
  evidence_name text,
  updated_at timestamptz not null default now(),
  unique (match_id, auth_user_id)
);
alter table public.manager_match_arrangements enable row level security;
drop policy if exists "Managers read own arrangement reports" on public.manager_match_arrangements;
create policy "Managers read own arrangement reports" on public.manager_match_arrangements for select to authenticated
using (
  auth.uid() = auth_user_id
  or exists (
    select 1 from public.matches m
    where m.id = match_id and public.can_assist_tournament(m.tournament_id)
  )
);
drop policy if exists "Managers insert own arrangement reports" on public.manager_match_arrangements;
create policy "Managers insert own arrangement reports" on public.manager_match_arrangements for insert to authenticated with check (auth.uid() = auth_user_id);
drop policy if exists "Managers update own arrangement reports" on public.manager_match_arrangements;
create policy "Managers update own arrangement reports" on public.manager_match_arrangements for update to authenticated using (auth.uid() = auth_user_id) with check (auth.uid() = auth_user_id);
-- Current state is mutated only by the validated RPCs below.
revoke insert, update, delete on public.manager_match_arrangements from authenticated;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('match-evidence','match-evidence',false,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=false,file_size_limit=8388608,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "Managers upload own match evidence" on storage.objects;
create policy "Managers upload evidence for owned arrangements" on storage.objects for insert to authenticated
with check (
  bucket_id='match-evidence'
  and (storage.foldername(name))[1]=auth.uid()::text
  and exists (
    select 1 from public.manager_match_arrangements a
    join public.tournament_entries e on e.id=a.tournament_entry_id
    join public.manager_portal_accounts p on p.manager_id=e.manager_id and p.auth_user_id=auth.uid() and p.active=true
    join public.matches m on m.id=a.match_id
    where a.auth_user_id=auth.uid()
      and (a.tournament_entry_id=m.home_entry_id or a.tournament_entry_id=m.away_entry_id)
      and a.match_id::text=(storage.foldername(name))[2]
      and storage.filename(name) in ('evidence-a.jpg','evidence-a.png','evidence-a.webp','evidence-a.gif','evidence-b.jpg','evidence-b.png','evidence-b.webp','evidence-b.gif')
      and array_length(storage.foldername(name),1)=2
  )
);
drop policy if exists "Managers read own match evidence" on storage.objects;
create policy "Managers and tournament staff read match evidence" on storage.objects for select to authenticated
using (
  bucket_id='match-evidence'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or exists (
      select 1
      from public.manager_match_arrangements a
      join public.matches m on m.id=a.match_id
      where a.evidence_path=name
        and public.can_assist_tournament(m.tournament_id)
    )
  )
);
drop policy if exists "Managers update own match evidence" on storage.objects;
drop policy if exists "Managers update evidence for owned arrangements" on storage.objects;

create table if not exists public.manager_match_arrangement_events (
  id bigint generated by default as identity primary key,
  arrangement_id bigint not null references public.manager_match_arrangements(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  tournament_entry_id bigint references public.tournament_entries(id) on delete set null,
  action text not null check (action in ('sent','received','chased','arranged','problem')),
  created_at timestamptz not null default now()
);
alter table public.manager_match_arrangement_events enable row level security;
drop policy if exists "Managers read own arrangement history" on public.manager_match_arrangement_events;
create policy "Managers and tournament staff read arrangement history" on public.manager_match_arrangement_events for select to authenticated
using (
  auth.uid() = auth_user_id
  or exists (
    select 1 from public.matches m
    where m.id = match_id and public.can_assist_tournament(m.tournament_id)
  )
);
-- Events are append-only through the SECURITY DEFINER RPC below. Clients cannot forge
-- an event against another manager's arrangement.
revoke insert, update, delete on public.manager_match_arrangement_events from authenticated;

drop policy if exists "Managers delete own match evidence" on storage.objects;
create policy "Managers delete superseded match evidence" on storage.objects for delete to authenticated
using (
  bucket_id='match-evidence'
  and (storage.foldername(name))[1]=auth.uid()::text
  and not exists (
    select 1 from public.manager_match_arrangements a
    where a.auth_user_id=auth.uid() and a.evidence_path=name
  )
);

create or replace function public.record_manager_match_arrangement_action(
  p_match_id bigint,
  p_tournament_entry_id bigint,
  p_status text
) returns public.manager_match_arrangements
language plpgsql security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_arr public.manager_match_arrangements;
  v_home_entry_id bigint;
  v_away_entry_id bigint;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_status not in ('sent','received','chased','arranged','problem') then raise exception 'Invalid arrangement status'; end if;
  if not exists (
    select 1
    from public.matches m
    join public.tournament_entries e on e.id=p_tournament_entry_id
    join public.manager_portal_accounts a
      on a.manager_id=e.manager_id and a.auth_user_id=v_user and a.active=true
    where m.id=p_match_id
      and e.tournament_id=m.tournament_id
      and (m.home_entry_id=e.id or m.away_entry_id=e.id)
  ) then raise exception 'You do not manage this tournament entry'; end if;

  -- Lock the fixture so it cannot become terminal between validation and write.
  select home_entry_id, away_entry_id into v_home_entry_id, v_away_entry_id
  from public.matches
  where id=p_match_id
    and coalesce(lower(status),'scheduled') not in ('played','forfeit','voided','cancelled')
  for update;
  if not found then raise exception 'This fixture is no longer active'; end if;

  if p_status in ('sent') and p_tournament_entry_id <> v_home_entry_id then
    raise exception 'Only the home manager can record a sent request';
  end if;
  if p_status in ('received','chased') and p_tournament_entry_id <> v_away_entry_id then
    raise exception 'Only the away manager can record a received request or chase';
  end if;
  if p_status not in ('sent','received','chased','problem') then
    raise exception 'This action is not available to managers';
  end if;

  insert into public.manager_match_arrangements(match_id,auth_user_id,tournament_entry_id,status,reported_at,updated_at)
  values(p_match_id,v_user,p_tournament_entry_id,p_status,now(),now())
  on conflict(match_id,auth_user_id) do update
    set status=excluded.status,
        tournament_entry_id=excluded.tournament_entry_id,
        updated_at=now()
  returning * into v_arr;

  insert into public.manager_match_arrangement_events(arrangement_id,match_id,auth_user_id,tournament_entry_id,action,created_at)
  values(v_arr.id,v_arr.match_id,v_arr.auth_user_id,v_arr.tournament_entry_id,p_status,now());

  return v_arr;
end;
$$;
revoke all on function public.record_manager_match_arrangement_action(bigint,bigint,text) from public;
grant execute on function public.record_manager_match_arrangement_action(bigint,bigint,text) to authenticated;

create or replace function public.attach_manager_match_evidence(
  p_match_id bigint,
  p_evidence_path text,
  p_evidence_name text
) returns public.manager_match_arrangements
language plpgsql security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_arr public.manager_match_arrangements;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_evidence_path is null
     or split_part(p_evidence_path,'/',1) <> v_user::text
     or split_part(p_evidence_path,'/',2) <> p_match_id::text
     or split_part(p_evidence_path,'/',3) not in (
       'evidence-a.jpg','evidence-a.png','evidence-a.webp','evidence-a.gif',
       'evidence-b.jpg','evidence-b.png','evidence-b.webp','evidence-b.gif'
     )
     or split_part(p_evidence_path,'/',4) <> '' then
    raise exception 'Invalid evidence path';
  end if;
  update public.manager_match_arrangements
     set evidence_path=p_evidence_path,evidence_name=p_evidence_name,updated_at=now()
   where match_id=p_match_id
     and auth_user_id=v_user
     and exists (
       select 1
       from public.tournament_entries e
       join public.manager_portal_accounts p
         on p.manager_id=e.manager_id and p.auth_user_id=v_user and p.active=true
       join public.matches m on m.id=manager_match_arrangements.match_id
       where e.id=manager_match_arrangements.tournament_entry_id
         and (manager_match_arrangements.tournament_entry_id=m.home_entry_id
              or manager_match_arrangements.tournament_entry_id=m.away_entry_id)
     )
   returning * into v_arr;
  if v_arr.id is null then raise exception 'Record an arrangement action before adding evidence'; end if;
  return v_arr;
end;
$$;
revoke all on function public.attach_manager_match_evidence(bigint,text,text) from public;
grant execute on function public.attach_manager_match_evidence(bigint,text,text) to authenticated;

create or replace function public.get_manager_match_evidence_path(p_arrangement_id bigint)
returns text
language plpgsql security definer
set search_path = public
as $$
declare
  v_path text;
begin
  select a.evidence_path into v_path
  from public.manager_match_arrangements a
  join public.matches m on m.id=a.match_id
  where a.id=p_arrangement_id
    and (a.auth_user_id=auth.uid() or public.can_assist_tournament(m.tournament_id));
  if not found then raise exception 'Evidence not found or access denied'; end if;
  return v_path;
end;
$$;
revoke all on function public.get_manager_match_evidence_path(bigint) from public;
grant execute on function public.get_manager_match_evidence_path(bigint) to authenticated;
